### ISSUE TITLE
argument "num.goats2" is missing, with no default

### ISSUE THREAD

**Issue by lecy** [Watts-College/paf-514-template#10]
I am trying to complete Lab 02 and when I change the numbers for the sets to 9 goats and 1 car, I get the following error after I run the whole code chunk:

```
Error in sample(x = rep(c("goat", "car"), c(num.goats2, num.cars2)), size = (num.goats2 + :
argument "num.goats2" is missing, with no default
```

It does not come up when I run that exact line, just when I get to the multiple iterations (code below).

```
results.df <- NULL # collector

for( i in 1:10000 ) # iterator
{
game.outcome <- play_game()
# binding step
results.df <- rbind( results.df, game.outcome )
}
```

I just cannot figure out what I am doing wrong. Could you please provide some guidance? Thank you!

**Comment by lecy** [comment]
You would need to share more code for a better diagnostic. The error is a function of how you implemented the code within that function (create_game?), and there are probably a dozen different implementations that would work and a thousand ways to do it incorrectly. 

But if I were a gambling person, I would guess that it is here: 

```
play_game()
```

Recall in the first setup we always had exactly 2 goats and 1 car, so those arguments could be hard coded into the game because they were constants. Now the user can build different sizes of games, so create_game() will need those two arguments. Since play_game() calls all the steps in order, you would need to include the game size argument in play_game() so you can pass them to create_game(). 

```
play_game <- function( goats.n, cars.n )
{
  game <- create_game( goats=goats.n, cars=cars.n )   # << args from play_game passed to here
  game.size <- length(game)
  door <- pick_door( game.size )
  etc. 

}
```

**Comment by DrKBoucher** [comment]
Here is the complete code:

rep( c("goat","car"), c( 3, 2 ) )
num.goats2 <- 9
num.cars2 <- 1
create_game <- function( num.goats2, num.cars2 )
{
  a.game <- sample( x=rep( c("goat","car"), c(num.goats2,num.cars2) ), 
                    size=(num.goats2+num.cars2), replace=F )
  return( a.game )
}

create_game( num.goats2=9, num.cars2=1 )
build_doors <- function( n ){ return( 1:n ) }

select_door <- function( game )
{
  doors <- build_doors( n=length(game) ) 
  a.pick <- sample( doors, size=1 )
  return( a.pick )  # number between 1 and N
}
build_doors <- function( n ){ return( 1:n ) }

create_game <- function( num.goats2, num.cars2 )
{
  a.game <- sample( x=rep( c("goat","car"), c(num.goats2,num.cars2) ), 
                    size=(num.goats2+num.cars2), replace=F )
  return( a.game )
}

select_door <- function( game )
{
  doors <- build_doors( n=length(game) ) 
  a.pick <- sample( doors, size=1 )
  return( a.pick )  # number between 1 and N
}

open_goat_door <- function( game, a.pick )
{
  doors <- build_doors( n=length(game) )
  doors.that.can.be.opened <- doors[ ! ( game == "car" | doors == a.pick ) ]
  opened.door <- sample( doors.that.can.be.opened, size=1 )
  return( opened.door ) # number between 1 and N
}

change_door <- function( stay=T, game, opened.door, a.pick )
{
  doors <- build_doors( length(game) )
  
  if( stay )
  {
    final.pick <- a.pick
  }
  if( ! stay )
  {
    available.doors <- doors[ doors != opened.door & doors != a.pick ]
    final.pick  <- sample( available.doors, size=1 ) 
  }
  
  return( final.pick )  
}

determine_winner <- function( final.pick, game )
{
  if( game[ final.pick ] == "car" )
  {
    return( "WIN" )
  }
  if( game[ final.pick ] == "goat" )
  {
    return( "LOSE" )
  }
}
num.goats2 <- 9
num.cars2 <- 1
this.game <- create_game( num.goats2, num.cars2 )
my.initial.pick <- select_door( game=this.game )
opened.door <- open_goat_door( this.game, my.initial.pick )

my.final.pick.stay <- change_door( stay=T, game=this.game, 
                                   opened.door=opened.door, a.pick=my.initial.pick )
my.final.pick.switch <- change_door( stay=F, game=this.game,
                                     opened.door=opened.door, a.pick=my.initial.pick )

game.outcome.stay <- determine_winner( final.pick=my.final.pick.stay, game=this.game )
game.outcome.switch <- determine_winner( final.pick=my.final.pick.switch, game=this.game )

play_game <- function( num.goats2, num.cars2 )
{
  new.game <- create_game(num.goats2, num.cars2)
  first.pick <- select_door()
  opened.door <- open_goat_door( new.game, first.pick )
  final.pick.stay <- change_door( stay=T, opened.door, first.pick )
  final.pick.switch <- change_door( stay=F, opened.door, first.pick )
  outcome.stay <- determine_winner( final.pick.stay, new.game  )
  outcome.switch <- determine_winner( final.pick.switch, new.game )
  
  strategy <- c("stay","switch")
  outcome <- c(outcome.stay,outcome.switch)
  game.results <- data.frame( strategy, outcome,
                              stringsAsFactors=F )
  return( game.results )
}

results.df <- NULL   # collector

for( i in 1:10000 )  # iterator
{
  game.outcome <- play_game()
  # binding step
  results.df <- rbind( results.df, game.outcome )
}

table( results.df ) 

table( results.df ) %>% 
  prop.table( margin=1 ) %>% 
  round( 2 )

**Comment by DrKBoucher** [comment]
Error in sample(x = rep(c("goat", "car"), c(num.goats2, num.cars2)), size = (num.goats2 +  : 
  argument "num.goats2" is missing, with no default

**Comment by lecy** [comment]
I think it is here: 

The **play_game()** function requires your goat and car count to work: 

```r
create_game <- function( num.goats2, num.cars2 )
{
  a.game <- sample( x=rep( c("goat","car"), c(num.goats2,num.cars2) ), 
                    size=(num.goats2+num.cars2), replace=F )
  return( a.game )
}
```

You added the arguments to **play_game()**, but you are not passing them to **create_game()**.

```r
play_game <- function( num.goats2, num.cars2 )
{
  new.game <- create_game()   # should be create_game(num.goats2, num.cars2)
  ...
}
```

Similarly, **select_door()** now needs to know the game size, which it gets from **game**, but you are not passing it from the results of the first step here: 

```r
select_door <- function( game )
{
  doors <- build_doors( n=length(game) ) 
  a.pick <- sample( doors, size=1 )
  return( a.pick )  # number between 1 and N
}

play_game <- function( num.goats2, num.cars2 )
{
  new.game <- create_game()
  first.pick <- select_door()   # should be select_door( new.game )
  ...
}
```

Does that make sense?
