### ISSUE TITLE
Final Lab Part III Step 1

### ISSUE THREAD

**Issue by ClaudiaHebert** [Watts-College/paf-514-template#102]
@castower I'm trying to create my generic salary template but having trouble with the step of the data wrangling functions. After sourcing the utils.R document and reading in the URL I have a chunk that reads: 

d %>% 
  get_first_name() %>% 
  add_gender() %>% 
  add_titles() %>% 
  convert_currency() %>% 
  make_salary_fte() %>% 
  get_study_sample() 

I've gotten a number of different errors when I run this chunk but it seems to be about the get_first_name() function which is saying "Error in strsplit(name, ",") : non-character argument." I tried with both my created function and the provided one and am receiving the same message. This is what mine looks like: 

add_gender <- function(d)
{
  d$first.name <- get_first_name(d$Full.Name) #extract first names 
  unique.first.names <- unique(d$first.name) #create a list of unique first names in the data
  gen <- gender(unique.first.names) #get gender data from US social security admin
  gen <- gen %>% 
    rename(first.name = name) #rename column for merge 
  d <- merge(d, gen, by = "first.name", all.x = TRUE) #merge gender table and salary data #left join
  d$gender[ is.na(d$gender) ] <- "uncoded" #change NAs to uncoded 
  d$gender <- factor( d$gender, levels=c("male","female","uncoded") ) #recode as factor 
  return(d)
}

Any thoughts? Or am I not setting up the data wrangling chunk correctly?

**Comment by bpiontek-asu** [comment]
@ClaudiaHebert I don't know if this will help, but I'm just writing these as individual steps in my template, without piping:

`d$first.name <- get_first_name( d$Full.Name )`
`d <- add_gender( d )`
`d <- add_titles( d )`
etc., for each function.

Maybe using a setup like that would help?

**Comment by castower** [comment]
Hello @ClaudiaHebert,

I took a look at the code you emailed over.

If you run just the beginning of your code you will see that the output is not returning a data set with first.name added to the data set:

```
d %>% 
  get_first_name() 
```

You'll want to ensure that you're extracting just the first names and adding them to your data set. Specifically, the code above should return your full data set with first.name added as a column. You can then use first.name in your add_gender() function.

Another option is to do similar to @bpiontek-asu's example and have get_first_name just return a list of first names. You can then assign that to d$first.name before moving on to the other functions.
