### ISSUE TITLE
Final Lab Parts 2/3 - Running the Report When an Academic Unit (i) Does Not Exist

### ISSUE THREAD

**Issue by bpiontek-asu** [Watts-College/paf-514-template#103]
Hi @castower, I am nearly done with my final lab, but am getting the following error when I try to run my batch file for years other than 2020:

> Error in plot.window(xlim = c(40000 - 10000, xmax), ylim = c(0, ymax +  : 
  need finite 'xlim' values

I went back to my manual testing file, and have realized that the error occurs when I have a case where one of the specified academic units does not appear for a given year (e.g.: the academic unit "Ldrshp and Integrative Studies" does not appear in the data for 2019 and the academic unit "CISA-Science & Mathmatics" does not appear in the data for 2016, etc.). 

What I think I need to figure out is how to get my loop to skip over cases where "i" does not exist in the data. 

I currently have
`  d %>%  
    filter( Department.Description == i ) %>% 
    create_salary_table() %>% 
    build_graph( unit=i )  `

But I think I need to figure out how to say
`  d %>%  
    filter( Department.Description == i  **where i exists** ) %>% 
    create_salary_table() %>% 
    build_graph( unit=i )  `

and I'm not sure how to do that.

Can you assist?

**Comment by ClaudiaHebert** [comment]
If I understood correctly, I think this bit was in the instructions, I took the code if( nrow(d2) == 0 ) { next } and put it in my loop right after the filter step. The next command simply skips to the next iteration of the loop. 

I haven't been able to run my batch file yet so not sure if this fixes it but worth a shot!

**Comment by bpiontek-asu** [comment]
@ClaudiaHebert Thank you so much! Not sure how I missed that in the instructions, but I definitely did!

@castower, when I update the code the way to inlcude the "if" statement (see below), the graph no longer prints. Can you help me find my error?

`  d %>%  
    filter( Department.Description == i )
    if( nrow(d) == 0 ) { next } %>% 
    create_salary_table() %>% 
    build_graph( unit=i )  `

**Comment by castower** [comment]
Hello @bpiontek-asu 
You'll notice in the example that d2 is assigned before the next step rather than connecting it with pipes:

```
for( i in academic.units )
{
  
  d2 <- filter( d, Department.Description == i )
  if( nrow(d2) == 0 ) { next }  
  # skips the rest of the code in the loop 
  # and start over with the next department
  ...
  
}
```

You can then do the rest of the steps using d2 with pipes after `if( nrow(d2) == 0 ) { next }  `.

**Comment by bpiontek-asu** [comment]
Thanks @castower!

I should have specified in my earlier comment that even when I use the following code, the graph still does not print:

`for( i in academic.units )`
`{`
`  cat( paste('<h1>', i ,'</h1>' ) )`

`  d2 <-  filter(d, Department.Description == i ) `
`    if( nrow(d2) == 0 ) { next } %>% `
`    create_salary_table() %>% `
`    build_graph( unit=i )  `

`  cat( paste('<h3>', 'PAY RANGE BY RANK AND GENDER' ,'</h3>' ) )`

`  t.salary <- `
`    d %>% `
 `   filter( Department.Description == i ) %>% `
`    create_salary_table()`
    
 ` cat( t.salary %>% knitr::kable(format="html") )`

`  cat( paste('<h3>', 'TOP 5 SALARIES' ,'</h3>' ) )`

`  t.five.salary <- `
`    d %>% `
`    filter( Department.Description == i ) %>% `
`    top_salary_table()`
    
`  cat( t.five.salary %>% knitr::kable(format="html") )`

`  cat( '<br><hr><br>' )`
  
`}
`

Instead, I get an output in RStudio that looks like the following, and nothing in my knitted html file:

> <h1> CISA-Intrdisp Hum & Comm </h1><h3> PAY RANGE BY RANK AND GENDER </h3>`summarise()` has grouped output by 'title'. You can override using the
`.groups` argument.
<table>
 <thead>
  <tr>
   <th style="text-align:left;"> title </th>
   <th style="text-align:left;"> gender </th>
   <th style="text-align:right;"> q25 </th>
   <th style="text-align:right;"> q50 </th>
   <th style="text-align:right;"> q75 </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> p </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Full Professor </td>
   <td style="text-align:left;"> male </td>
   <td style="text-align:right;"> 104050.0 </td>
   <td style="text-align:right;"> 108100 </td>
   <td style="text-align:right;"> 126855.00 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0.07 </td>
  </tr>  
  <tr>
   <td style="text-align:left;"> Full Professor </td>
   <td style="text-align:left;"> female </td>
   <td style="text-align:right;"> 154012.5 </td>
   <td style="text-align:right;"> 201675 </td>
   <td style="text-align:right;"> 249337.50 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0.04 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Associate Professor </td>
   <td style="text-align:left;"> male </td>
   <td style="text-align:right;"> 94612.0 </td>
   <td style="text-align:right;"> 94612 </td>
   <td style="text-align:right;"> 94612.00 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.02 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Associate Professor </td>
   <td style="text-align:left;"> female </td>
   <td style="text-align:right;"> 88762.5 </td>
   <td style="text-align:right;"> 89225 </td>
   <td style="text-align:right;"> 89687.50 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0.04 </td>
  </tr>
  <tr>
  <td style="text-align:left;"> Assistant Professor </td>
   <td style="text-align:left;"> male </td>
   <td style="text-align:right;"> 73512.5 </td>
   <td style="text-align:right;"> 74025 </td>
   <td style="text-align:right;"> 74512.50 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0.07 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Assistant Professor </td>
   <td style="text-align:left;"> female </td>
   <td style="text-align:right;"> 72100.0 </td>
   <td style="text-align:right;"> 72200 </td>
   <td style="text-align:right;"> 74375.00 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0.07 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Assistant Professor </td>
   <td style="text-align:left;"> uncoded </td>
   <td style="text-align:right;"> 65000.0 </td>
   <td style="text-align:right;"> 65000 </td>
   <td style="text-align:right;"> 65000.00 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.02 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Teaching Faculty </td>
   <td style="text-align:left;"> male </td>
   <td style="text-align:right;"> 48218.0 </td>
   <td style="text-align:right;"> 48740 </td>
   <td style="text-align:right;"> 48897.00 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 0.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Teaching Faculty </td>
   <td style="text-align:left;"> female </td>
   <td style="text-align:right;"> 47337.5 </td>
   <td style="text-align:right;"> 48845 </td>
   <td style="text-align:right;"> 51706.25 </td>
   <td style="text-align:right;"> 20 </td>
   <td style="text-align:right;"> 0.44 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Teaching Faculty </td>
   <td style="text-align:left;"> uncoded </td>
   <td style="text-align:right;"> 48980.0 </td>
   <td style="text-align:right;"> 48980 </td>
   <td style="text-align:right;"> 48980.00 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.02 </td>
  </tr>
</tbody>
</table><h3> TOP 5 SALARIES </h3><table>
 <thead>
  <tr>
   <th style="text-align:left;"> Full.Name </th>
   <th style="text-align:left;"> gender </th>
   <th style="text-align:left;"> Job.Description </th>
   <th style="text-align:left;"> salary </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Rhodes, Jewell </td>
   <td style="text-align:left;"> female </td>
   <td style="text-align:left;"> Professor </td>
   <td style="text-align:left;"> $297,000 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Simpson, Brooks </td>
   <td style="text-align:left;"> male </td>
   <td style="text-align:left;"> Professor </td>
   <td style="text-align:left;"> $145,610 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Maid, Barry </td>
   <td style="text-align:left;"> male </td>
   <td style="text-align:left;"> Professor </td>
   <td style="text-align:left;"> $108,100 </td>
  </tr>
  <tr>
<td style="text-align:left;"> Brumberger, Eva </td>
   <td style="text-align:left;"> female </td>
   <td style="text-align:left;"> Professor </td>
   <td style="text-align:left;"> $106,350 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Moulton, Ian </td>
   <td style="text-align:left;"> male </td>
   <td style="text-align:left;"> Professor </td>
   <td style="text-align:left;"> $100,000 </td>
  </tr>
</tbody>

And so on, but for each individual unit, although my t.salary and t.five.salary tables still display in the knitted html.

I have also tried the following code, and get the similar result, although my tables no longer display in a meaningful way.

`for( i in academic.units )`
`{`
`  cat( paste('<h1>', i ,'</h1>' ) )`
  
`  d2 <-  filter(d, Department.Description == i ) `
`    if( nrow(d2) == 0 ) { next } %>% `
`    create_salary_table() %>% `
`    build_graph( unit=i )  `

`  cat( paste('<h3>', 'PAY RANGE BY RANK AND GENDER' ,'</h3>' ) )`

`  t.salary <- `
`    filter(d, Department.Description == i ) `
`    if( nrow(d2) == 0 ) { next } %>% `
`    create_salary_table()`
    
`  cat( t.salary %>% knitr::kable(format="html") )`

`  cat( paste('<h3>', 'TOP 5 SALARIES' ,'</h3>' ) )`

`  t.five.salary <- `
`    filter(d, Department.Description == i ) `
`    if( nrow(d2) == 0 ) { next } %>% `
`    top_salary_table()`
    
`  cat( t.five.salary %>% knitr::kable(format="html") )`

`  cat( '<br><hr><br>' )`
  
`}`

**Comment by bpiontek-asu** [comment]
@castower, Interestingly, I see that the output that I copied in from RStudio renders as html code for meaningful tables here in the issue tracker, but I'm not sure how that ties to my issue with the graphs not printing.

**Comment by castower** [comment]
@bpiontek-asu 

Have you set your code chunk option to have results='asis'?

That should allow the knitted file to embed the HTML.

**Comment by bpiontek-asu** [comment]
@castower, Yes, it's set as "{r, fig.height=7, fig.width=10, results="asis"}"

**Comment by castower** [comment]
@bpiontek-asu 

Hmm, it should produce the code if you remove the pipes after the `if( nrow(d2) == 0 ) { next } ` step. 

Your pipes should only be connected to the data sets.

**Comment by bpiontek-asu** [comment]
@castower, thank you SO much!
