### ISSUE TITLE
Module 3 Lecture Note Links - Access Denied 

### ISSUE THREAD

**Issue by Rachel-Judd** [Watts-College/paf-514-template#12]
Hello,
I'm wondering if anyone else has had issues opening the links in the lecture notes for this week? When I click on "Chapter", "Slides", and "Character Encoding"  it takes me to a canvas page that says Access Denied. These are the links. Just want to make sure I'm not missing any important materials. 

https://canvas.asu.edu/courses/139186/files/58468123/preview

https://canvas.asu.edu/courses/139186/files/58468143/preview

https://canvas.asu.edu/courses/139186/files/61238802/preview

**Comment by lecy** [comment]
I get the same error but that is not our course.  We are number 166594: 

https://canvas.asu.edu/courses/166594/pages/m3-overview-and-learning-materials?module_item_id=11793410

Where did you reach those links? If they were internal links from within Canvas I would like to make sure they are fixed.

**Comment by Rachel-Judd** [comment]
https://cdn.inst-fs-iad-prod.inscloudgate.net/a6359e24-24bd-4758-8284-e5660390cc62/module-03.html?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImNkbiJ9.eyJyZXNvdXJjZSI6Ii9hNjM1OWUyNC0yNGJkLTQ3NTgtODI4NC1lNTY2MDM5MGNjNjIvbW9kdWxlLTAzLmh0bWwiLCJ0ZW5hbnQiOiJjYW52YXMiLCJ1c2VyX2lkIjoiNzIzNjAwMDAwMDA4OTIwOTIiLCJpYXQiOjE2OTM4NzU2ODUsImV4cCI6MTY5Mzk2MjA4NX0.3-6REqiy4BxzycEUAV0cOYQY1fccZ5c44acjinISolOGUcRNkJ3yn4-t-nJuB8LO-YTzvRwQGEsJo7hAL0l3ew&content_type=text%2Fhtml

**Comment by lecy** [comment]
I’ll look into it more but in the meantime the content is definitely available here: 

https://watts-college.github.io/cpp-527-template/schedule/

**Comment by lecy** [comment]
@jbpratt1 any ideas about what might be causing that behavior? I can’t replicate the issue on my end.

**Comment by jbpratt1** [comment]
@Rachel-Judd and @lecy, thanks of bringing this to my attention. This should not be corrected. Please retry visiting the page via the [M3 Overview & Learning Materials](https://canvas.asu.edu/courses/166594/pages/m3-overview-and-learning-materials) and revisiting the [Module 3 Lecture Notes](https://watts-college.github.io/paf-514-template/lectures/week-03/) link.

Let me know if you encounter any similar issues in the future.

**Comment by lecy** [comment]
Thanks!
