### ISSUE TITLE
Lab 03 - Question 2-b

### ISSUE THREAD

**Issue by gmendez9** [Watts-College/paf-514-template#15]
Hi -

I am posting my code for 2-b, as I suspect something is not right here because I get a length warning when running my loop. There must be something I am missing here. Hoping to identify my mistake(s):

```{r}
#titles <- d$titlenew
first.six.titles <- d$titlenew

# x is a single title
get_first_word <- function( x )
{
 word.list <- strsplit( first.six.titles, " " ) # split title x into words
 word.count <- lapply( word.list, length )
  word.count <- unlist( word.count ) # convert to a vector# unlist results
  xy <- sub("([A-Za-z]+).*", "\\1",      # Extract first word
                       word.count)
return(xy)
}

# test your function
x <- d$titlenew[1]
get_first_word( x )


```

Respectfully,
G.M

**Comment by gmendez9** [comment]
Printing the first few results:
   [1] "9"  "9"  "5"  "10" "8"  "8"  "3"  "7"  "7"  "6"  "10" "5"  "5"  "3"  "5"  "5"  "5"  "9"  "4"  "5" 
  [21] "16" "10" "11" "13" "8"  "9"  "4"  "4"  "5"  "8"  "15" "7"  "7"  "4"  "5"  "6"  "9"  "10" "8"  "4" 
  [41] "8"  "4"  "4"  "7"  "6"  "3"  "8"  "7"  "9"  "9"  "6"  "8"  "4"  "3"  "6"  "5"  "12" "2"  "4"  "10"
  [61] "7"  "6"  "8"  "4"  "4"  "9"  "8"  "7"  "10" "19" "4"  "6"  "9"  "6"  "7"  "3"  "6"  "10" "9"  "10"

**Comment by lecy** [comment]
It looks good up until the sub() function.

If you print out **word.count** does it look correct?

You can take a subset of a vector using positions.

```r
x[ 1 ] # x[ first ]
x[ length(x) ] # x[ last ]
```

**Comment by gmendez9** [comment]
Here's a sample of printed results, Is this what we are looking for?

```{r}
[[665]]
[1] 9

[[666]]
[1] 7

[[667]]
[1] 11

[[668]]
[1] 2

[[669]]
[1] 9

[[670]]
[1] 10

```

**Comment by lecy** [comment]
Remember that functions help you manage your workflow. Give some thought to the work that the function will be doing, especially the unit of input (a singe string, a vector, a data frame?). 

You are violating the rules here by sending the function an argument X, then using something else completely inside the function: 

```r
first.six.titles <- d$titlenew

# x is a single title
get_first_word <- function( x )
{
 word.list <- strsplit( first.six.titles, " " )   # not using X here
 word.count <- lapply( word.list, length )
  word.count <- unlist( word.count ) # convert to a vector# unlist results
  xy <- sub("([A-Za-z]+).*", "\\1",      # Extract first word
                       word.count)
```
It will help to restructure your code a bit - start with a working "recipe" (linear steps), make sure they work, THEN turn them into a function: 

```r
x <- d$titlenew[1]  # first title
word.list <- strsplit( x, " " )   
word.vec <- unlist( word.list ) # convert to a vector
first.word <- word.vec[ 1 ] # select first word
first word

x <- d$titlenew[2]  # try with different title
word.list <- strsplit( x, " " )   
word.vec <- unlist( word.list ) # convert to a vector
first.word <- word.vec[ 1 ] # select first word
first word
```

Once it's working, then you can put it into a function:

```r
get_first_word <- function(x) {
  word.list <- strsplit( x, " " )   
  word.vec <- unlist( word.list )
  first.word <- word.vec[ 1 ] 
  return(first.word)
}

# apply the function to all titles
lapply( titles, get_first_word )
```

**Comment by gmendez9** [comment]
I see where I made the wrong turns, thank you.
