### ISSUE TITLE
R Package has_dev1()

### ISSUE THREAD

**Issue by JJSpaeth** [Watts-College/paf-514-template#16]
Hello, 
I'm stuck at the very start, the devtools are not installing correctly.  This is what I've done in R:

> install.packages(c("devtools", "roxygen2","usethis","testthat","knitr"))
Installing packages into ‘C:/Users/spaet/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
also installing the dependency ‘whisker’

trying URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.3/whisker_0.4.1.zip'
Content type 'application/zip' length 83440 bytes (81 KB)
downloaded 81 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.3/devtools_2.4.5.zip'
Content type 'application/zip' length 435820 bytes (425 KB)
downloaded 425 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.3/roxygen2_7.2.3.zip'
Content type 'application/zip' length 1054938 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.3/usethis_2.2.2.zip'
Content type 'application/zip' length 897218 bytes (876 KB)
downloaded 876 KB

trying URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.3/testthat_3.1.10.zip'
Content type 'application/zip' length 2219745 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://mirror.las.iastate.edu/CRAN/bin/windows/contrib/4.3/knitr_1.43.zip'
Content type 'application/zip' length 1504857 bytes (1.4 MB)
downloaded 1.4 MB

package ‘whisker’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked
package ‘roxygen2’ successfully unpacked and MD5 sums checked
package ‘usethis’ successfully unpacked and MD5 sums checked
package ‘testthat’ successfully unpacked and MD5 sums checked
package ‘knitr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\spaet\AppData\Local\Temp\RtmpmqhaiA\downloaded_packages
> library(devtools)
Loading required package: usethis
> has_devel()
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
> pkgbuild::check_build_tools(debug = TRUE)
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

**Comment by JJSpaeth** [comment]
After intensive googling if you just suppress the build.tools check it seems to work fine:

> options(buildtools.check = function(action) TRUE )
> has_devel()
Your system is ready to build packages!

**Comment by lecy** [comment]
Are you on a Mac or PC? It might be related to your OS. You can see the different suggestions for Mac users here: 

https://www.r-project.org/nosvn/pandoc/devtools.html
