### ISSUE TITLE
R Package Functioning

### ISSUE THREAD

**Issue by DrKBoucher** [Watts-College/paf-514-template#17]
I am at the point where I am testing out my package. When I type 
library( montyhall )
create_game()
It does, in fact, create a new game appropriately. select_door works as well. But when I get to open_goat_door, I get the following errors:

> open_goat_door()
Error in open_goat_door() : argument "game" is missing, with no default
> change_door()
Error in change_door() : argument "a.pick" is missing, with no default
> determine_winner()
Error in determine_winner() : argument "game" is missing, with no default

I'm not sure if that's how it is supposed to work or not since the function is dependent on the functions prior but I was running them in order from start to finish. 

play_game works as intended. play_n_games seems to also work. 

Is this what is supposed to happen?

**Comment by tbnaes** [comment]
Mine does the same thing. I tried an explicit statement in the function for the package (game = game, a.pick = a.pick) and had a different error. Everything works in my R package except for those three run by themselves.

**Comment by JJSpaeth** [comment]
Those functions require an argument to be made to work properly.

open_goat_door <- function( game, a.pick )

In this case, you can't open a goat door if you don't have a door picked or goats behind them.  You have to tell the function how the game is set up and what door was picked.

Here is how that function is tested in the instructions for lab 01:

"# test it

this.game <- create_game()

this.game

my.initial.pick <- select_door()

my.initial.pick

open_goat_door( this.game, my.initial.pick )"

Respectfully,
John Spaeth

**Comment by tbnaes** [comment]
John, 

That is what I had to do to make those individual functions work outside of my R package, but I am wondering if you were successful in modifying the problem code given to the class in order to account for the need of assigned objects. While those three functions don't work on their own, the entire R package works perfectly together when play_n_games() is called.

**Comment by JJSpaeth** [comment]
You don't have to modify the code given in the package template, you just have to assign those values.  The function cannot work as intended without those assigned values. Here is what I typed in R after I created and loaded my package:

> this.game <- create_game()
> this.game
[1] "goat" "car"  "goat"
> my.initial.pick <- select_door()
> my.initial.pick
[1] 3
> open_goat_door(this.game, my.initial.pick)
[1] 1
