### ISSUE TITLE
Updating Error

### ISSUE THREAD

**Issue by ashleycc33** [Watts-College/paf-514-template#18]
Hi guys,

I'm getting this error when trying the intall() command:

```r
setwd( ".." ) 
> getwd()         
[1] "/Users"
> devtools::install( "montyhall" )
Error in `package_file()`:
! montyhall is not a directory.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `package_file()`:
! montyhall is not a directory.
---
Backtrace:
    ▆
 1. └─devtools::install("montyhall")
 2.   └─devtools::as.package(pkg)
 3.     └─devtools::package_file(path = x)
Run rlang::last_trace(drop = FALSE) to see 2 hidden frames
```

**Comment by ashleycc33** [comment]
Ok, now it's all messed up. I think I accidentally moved it elsewhere

**Comment by ashleycc33** [comment]
Ok, I restarted it and still had issues at this point.

Here is the error:
Error in data.frame(package = deps, installed = inst_ver, available = cran_ver,  : 
  row names contain missing values

**Comment by lecy** [comment]
You can check for your current path by: 

```r
getwd()
```

See the files in your directory by: 

```r
dir()
```

And you can always use an absolute path: 

```r
devtools::install( "C:/Users/name/projects/montyhall" )
```

Alternatively: 

```r
setwd( "C:/Users/name/projects" )
devtools::install( "montyhall" )
```

Another trick is to save your project directory. Before creating the package folder you can say:

```r
proj.dir <- getwd() # stores whatever is printed when you type getwd()
```

Then when you need to return to the root directory just call: 

```r
setwd( proj.dir )
```
