### ISSUE TITLE
Lab 5 Lecture Notes "required materials"

### ISSUE THREAD

**Issue by mbrentli** [Watts-College/paf-514-template#21]
I'm finding that the links for all of the 'required reading' in module 5 are broken (except for the wikipedia one).  I checked both the Canvas Links and the course page on Github.  

Has anyone else found this?  Or found a workaround?

![image](https://github.com/Watts-College/paf-514-template/assets/121507825/45c9ff85-a995-40ed-accb-14d7399b373e)

**Comment by lecy** [comment]
Please try these versions: 

https://web.archive.org/web/20230327153805/https://www.internetingishard.com/html-and-css/basic-web-pages/

https://web.archive.org/web/20230219140133/https://www.internetingishard.com/html-and-css/hello-css/

https://web.archive.org/web/20230327153805/https://www.internetingishard.com/html-and-css/responsive-design/

**Comment by lecy** [comment]
It looks like the base URL changed - the current versions are here: 

https://internetingishard.netlify.app/

https://internetingishard.netlify.app/html-and-css/basic-web-pages/

https://internetingishard.netlify.app/html-and-css/hello-css/

https://internetingishard.netlify.app/html-and-css/responsive-design/
