### ISSUE TITLE
Lab 05 - Step 5: Github page not  updating.

### ISSUE THREAD

**Issue by JJSpaeth** [Watts-College/paf-514-template#22]
Hello,
My original table-demo.md had too much text (I had copied the entire page) and no picture of Ryan Reynolds and Ryan Gosling. I since update the page but the new version will not publish.

https://jjspaeth.github.io/blog/table-demo/

I tried renaming it to table-demo2, I tried deleting it and creating a new one, I tried unpublishing the page and republishing it. No matter what I do it will not load the correct version. 

What is there left to try?

Respectfully,
John Spaeth

**Comment by lecy** [comment]
I can see the page. It looks like the text is a very light blue so hard to read. 

For pictures you would need to add them to your website directory and update the path.

**Comment by JJSpaeth** [comment]
That's the old version of the page, I've changed the color to a darker one and added the picture, but nothing I've done will get github to load the new version of the page.

**Comment by JJSpaeth** [comment]
Okay it is finally showed up!

**Comment by lecy** [comment]
That’s a good looking website!
