### ISSUE TITLE
Lab 6 Part 2 (CV)

### ISSUE THREAD

**Issue by mbrentli** [Watts-College/paf-514-template#24]
I'm getting stuck at Step 5,  I think (?)

I followed the instructions to clone, and have the files on my local computer, and have edited the necessary things and rendered the RMD to HTML and it is working.

I cannot find where to 'activate the GitHub page for this repository'.  When I go to my Github account in the desktop version, it looks like it is still the DS4PS one and after editing, I get this error that says "you don't have write access to cv":

![image](https://github.com/Watts-College/paf-514-template/assets/121507825/a8e74d9b-1218-4688-badc-2e78b55fb517)

When I go to the online version of GitHub, this cloned repository is no where to be found there.

So I am able to see the raw files on my computer and edit them, but it doesn't seem that anything is linked into a Github repository.

Did I miss a step (or two or three?)

**Comment by lecy** [comment]
I blame microsoft. 

The cloning functionality is now behind a templates feature. You should have seen a new repo called CV created in your GitHub account. That is what you would be pushing files to. 

I activated the templates feature so it should work now but you probably don't want to start over. If you can't find a CV repo in your GitHub account create one with that name, go back to GitHub desktop and clone that new repo, copy your files into it and push them to the server. 

Just don't copy the folder called .git. You will have a new one in your new CV repo. That contains the history of your activities, not files you need for the site.

**Comment by lecy** [comment]
If you are just starting the assignment you can select "use the template" instead of "clone" and it will copy all of the files to your personal GitHub account: 

![image](https://github.com/Watts-College/paf-514-template/assets/1209099/89b15302-b608-4582-a08b-5526b2650ddd)

You can then clone your own site in GitHub desktop, edit files, then push them back to your personal CV repo.

**Comment by mbrentli** [comment]
So I just started over and did the "use the template" option.  I had made a copy of the csv so it wasn't too laborious to just delete everything and start over.

Now it's in my repository list and I can push the changes from the desktop to the online repo, but I'm confused about being able to 'view your HTML resume online' and being able to 'Update the description section at the top right of your GitHub repo and add the link to your resume.'

When i click on the resume.html file, this is what I get:

![image](https://github.com/Watts-College/paf-514-template/assets/121507825/03afe65f-d372-4975-bbd7-a216a2e87339)

Is there a different way that I'm supposed to access/'view your HTML resume online'?

**Comment by lecy** [comment]
Yes, the html file will be here: 

https://github.com/DS4PS/cv/blob/master/index.html

But that will show you the html code - not that helpful. You need to activate your GitHub website (select the main branch, select root as your folder). Then when you visit the site this is what you will see: 

https://ds4ps.org/cv/

By default, websites always open to the index.html or home.html file. That is the landing page. Note that the CV version is named index.rmd / index.html here, so the preview the resume version we would visit that link (file called resume.html in the same folder):  

https://ds4ps.org/cv/resume.html

**Comment by lecy** [comment]
When you activate the pages website option GitHub will convert MD files to HTML on their servers. You don't see the HTML files in your project folder - it is all rendered behind the scenes. 

This is not the case for RMD files, however. They require running R code and GitHub will not have R preconfigured on their servers. As a result, those files are knitted locally and you push the HTML versions to GitHub. 

That is why you see paired resume.rmd / resume.html files but you do not see the HTML version of MD files.

**Comment by mbrentli** [comment]
OK, thanks - I got this one to work :)
