### ISSUE TITLE
Final Project - Part 3

### ISSUE THREAD

**Issue by mbrentli** [Watts-College/paf-514-template#28]
I've made it all the way to Part 3 of the final project, and pretty much up to Step 3 (I think).

I'm having a hard time understanding how the salary_report.rmd and batch.R file are working together.  From just following the project instructions, when I try to knit the salary_report, I'm getting "Error: ! object 'params' not found"  so I'm assuming there's a missing input or reference somewhere, but I can't figure it out.

I'm having a hard time wrapping my head around this last part of the project and how all these pieces are connected.

I would appreciate any direction anyone could provide!

**Comment by lecy** [comment]
Are you trying to knit it in R Studio? 

If you want to knit to test it out, comment out the line with params and add a line with the regular data load statement.

**Comment by gmendez9** [comment]
Hi , I had a similar issue and used this :

https://stackoverflow.com/questions/28432607/pandoc-version-1-12-3-or-higher-is-required-and-was-not-found-r-shiny/29710643#29710643
