### ISSUE TITLE
merging

### ISSUE THREAD

**Issue by Rachel-Judd** [Watts-College/paf-514-template#29]
HI,

I am having some issues with getting the tables to merge. When I use the code below it says there are 0 rows in d1. What am I missing? 
```
add_gender<-function()
{
library( gender )
  
d$first <- get_first_name(d$Full.Name)
unique.first.names <- unique( d$first)
unique.first.names<-as.character(unique.first.names)

gen <- gender( unique.first.names )
#head( gen ) %>% pander()
d$name<-d$first #rename to match 
d$gender <- factor(d$gender, levels=c("male","female","uncoded"))

#d1<- dplyr::join_left(d, gen, by="name", all.x=TRUE)
d1<-merge( d, gen, all.x=TRUE, by=c("name","gender") )
d1$gender.y[ is.na(d1$gender.y) ] <- "uncoded"
head(d1)
}
add_gender()

**Comment by lecy** [comment]
Can you print a glimpse of your two data frames **gen** and **d** prior to the merge?

```r
head( gen ) %>% knitr::kable()
head( d) %>% knitr::kable()
```

**Comment by gmendez9** [comment]
Similar Issue - I believe the prop columns are not populating, as noted in the code here. As per the instructions, I think this is unexpected behavior? 

Sharing my code below:

### Step three - Add Gender to the Dataset 

```{r}

 d <- add_gender(d) ## only 8 variables - compared to 10 columns in lab instructions (my output), we do get coding for names properly , however

```

Here's my function :

```{r}

add_gender <- function( d )
{
  
  library( gender )
  
  # need to save first names for the merge 
  d$first.name <- get_first_name( name=d$Full.Name ) # added 
  
  unique.first.names <- unique( d$first.name )
  
  unique.first.names<-as.character(unique.first.names) # added 
  
  gen <- gender( unique.first.names )
  gen <- dplyr::select( gen, name, gender )
  d <- merge( d, gen, by.x="first.name", by.y="name", all.x=TRUE )
  d$gender[ is.na(d$gender) ] <- "uncoded"
  d$gender <- factor( d$gender, levels=c("male","female","uncoded") )
  return(d)
}

```

Here's my df's before merge 


```{r}
head( gen ) %>% knitr::kable()
head( d) %>% knitr::kable()
```

|name  | proportion_male| proportion_female|gender | year_min| year_max|
|:-----|---------------:|-----------------:|:------|--------:|--------:|
|Aaron |          0.9918|            0.0082|male   |     1932|     2012|
|Abba  |          1.0000|            0.0000|male   |     1932|     2012|
|Abbey |          0.0017|            0.9983|female |     1932|     2012|
|Abbie |          0.0088|            0.9912|female |     1932|     2012|
|Abby  |          0.0030|            0.9970|female |     1932|     2012|
|Abdel |          1.0000|            0.0000|male   |     1932|     2012|



| Calendar.Year|Full.Name                           |Job.Description            |Department.Description         |Salary      | FTE|
|-------------:|:-----------------------------------|:--------------------------|:------------------------------|:-----------|---:|
|          2020|ABBASI, Mohammad                    |Research/Lab Assistant     |Sch Biological & Hlth Sys Engr |$35,090.00  | 100|
|          2020|ARQUIZA, Jose Maria Reynaldo Apollo |Lecturer                   |Sch Biological & Hlth Sys Engr |$71,400.00  | 100|
|          2020|Aaberg, Kelsea                      |Student Support Specialist |Admission Services             |$36,000.00  | 100|
|          2020|Abadjivor, Enyah                    |Project Manager            |CASGE  Tempe                   |$64,000.00  | 100|
|          2020|Abayesu, Precious                   |Management Intern          |Health & Clinical Partnerships |$20,800.00  |  50|
|          2020|Abbas, James                        |Assoc Professor            |Sch Biological & Hlth Sys Engr |$107,195.00 | 100|

**Comment by lecy** [comment]
My guess was the merge was not working because of different versions of the variable "name" in the two datasets. Note the difference here: 

```r
d1<- dplyr::join_left(d, gen, by="name", all.x=TRUE)
d1<-merge( d, gen, all.x=TRUE, by=c("name","gender") )
```

vs 

```r
d <- merge( d, gen, by.x="first.name", by.y="name", all.x=TRUE )
```

**Comment by Rachel-Judd** [comment]
head(gen) %>% knitr::kable()
![image](https://github.com/Watts-College/paf-514-template/assets/121843126/708ac027-f118-4acf-a84a-23e24d2ff564)

head(d) %>% knitr::kable()
![image](https://github.com/Watts-College/paf-514-template/assets/121843126/cec97276-cf52-4142-b2d6-2e303a2ec78a)

This does seem to be working now:
```
library( gender )

d$first <- get_first_name(d$Full.Name)
#d$name<-as.character(d$first)
unique.first.names <- unique( d$first)
unique.first.names<-as.character(unique.first.names)
d$name<-d$first
gen <- gender( unique.first.names )
head(gen) %>% knitr::kable()

head(d) %>% knitr::kable()
head(gen) %>% knitr::kable()


#d1<- dplyr::join_left(d, gen, by="name", all.x=TRUE)
d<-merge( d, gen, all.x=TRUE, by="name")
d$genderd <- factor(c("male","female","uncoded"))
d$gender[ is.na(d$gender) ] <- "uncoded"
head(d)
```
![image](https://github.com/Watts-College/paf-514-template/assets/121843126/885753a5-e32e-4426-be05-01ec2a31e4cd)

**Comment by lecy** [comment]
The "key" variables used to link datasets are the really important detail for joins. Specifically, just make sure the difference between these cases are clear: 

```r
merge( d, gen, by="name" )
merge( d, gen, by.x="first.name", by.y="name" )
```

One very easy way to destroy your dataset is to join on IDs that are not unique, usually when there is a time element in the data (multiple observations for the same person over time). I can't emphasize enough to pay attention to your join steps. Check dimensions before joins and after joins to make sure you have not corrupted the data during that step since it is really easy.  

http://ds4ps.org/dp4ss-textbook/p-076-merging-data.html

![image](https://github.com/Watts-College/paf-514-template/assets/1209099/73cd743c-9a4c-4f77-9e18-ed2f47f86889)

![image](https://github.com/Watts-College/paf-514-template/assets/1209099/602e1d07-f83c-4904-8e9e-dbad4e0801cb)

**Comment by gmendez9** [comment]
For my case - I just had to rework my code.

```{r}


library( gender )

# need to save first names for the merge 
d$first.name <- get_first_name( name=d$Full.Name )

# create a list of unique first names in the data 
unique.first.names <- unique( d$first.name )

# get gender data from US Social Security Admin 
gen <- gender( unique.first.names )
#head( gen ) %>% pander()

head( gen ) %>% knitr::kable()
head( d) %>% knitr::kable()

d <- add_gender_alt(d)

```
