### ISSUE TITLE
Part 2 - All departments in a Loop

### ISSUE THREAD

**Issue by gmendez9** [Watts-College/paf-514-template#30]
Hi - 

I am a bit stuck on the loop construction for Part II, I get the following message. All other outputs are consistent with Lab Instructions up to this stage: "Warning: Unknown or uninitialised column: `title`.Warning: Unknown or uninitialised column: `q50`.Warning: no non-missing arguments to max; returning -InfWarning: Unknown or uninitialised column: `n`.Error in plot.window(xlim = c(40000 - 10000, xmax), ylim = c(0, ymax +  : 
  need finite 'xlim' values"

It appears I am able to create "d2", but run into the error after piping to create_salary_table. Help is appreciated, sharing my code below:

## Part Two - All Departments in a Loop 

```{r, fig.height=7, fig.width=10, results="asis"}


for( i in academic.units )
{
  
  d2 <- filter( d, Department.Description == i ) %>%
create_salary_table() %>%   # create the salary summary by rank & gender table 
 get_top_five() %>%   # create the top 5 salaries table 
      build_graph(unit = i)   # build the graph  
  # print the tables:  
   cat( paste('<h3>',"TOP FIVE SALARIES",'</h3>' ) )
   cat( t.rank %>% knitr::kable(format="html") )   

   cat( '<br><hr><br>' )
  
}


for( i in academic.units )
{
  
  d2 <- filter( d, Department.Description == i )
  if( nrow(d2) == 0 ) { next }  
  # skips the rest of the code in the loop 
  # and start over with the next department
  ...
  
}


```

**Comment by lecy** [comment]
Check your salary statistics please. 

```r
summary(salary)
```

do you have infinite values?

**Comment by gmendez9** [comment]
Hi Professor Lecy,

I ran the initial summary, with no indication of infinite values - so I ran is.infinite after some exploration.

Here's the initial console output:

 Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  88500  114456  157695  167597  214082  288818 


```{r}
is.infinite(d2$salary)
```

 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[18] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE


Therefore - I kept modifying my code, here is the result: 

```{r, fig.height=7, fig.width=10, results="asis"}

 # 'academic.units'
academic.units <- 
    c("CISA-Intrdisp Hum & Comm", "CISA-Science & Mathmatics", 
      "College of Health Solutions MS", "College of Health Solutions NT", 
      "College of Health Solutions SH", "College Of Law", "English", "Hugh Downs School Of Comm", 
      "Humanities Arts & Cultural", "Journalism & Mass Comm", "Ldrshp and Integrative Studies", 
      "Math & Natural Sciences Div", "MDT Music", "Physics Department", 
      "Psychology", "Sch Biological & Hlth Sys Engr", "Sch Compt Infor & Dec Sys Engr", 
      "Sch Elect Comptr & Energy Engr", "Sch Engr Matter Trnsprt Energy", 
      "Sch Future of Innov in Society", "Sch Sustain Engr & Built Envrn", 
      "School Of Art", "School of Criminology & Crim J", "School Of Earth & Space Explor", 
      "School of Geog Sci & Urban Pln", "School of Math & Stat Sciences", 
      "School of Molecular Sciences", "School of Politics & Global St", 
      "School Of Public Affairs", "School of Social Transform", "School Of Social Work", 
      "SHPRS History Faculty", "Social & Behavioral Sciences", "Sols Administration & Faculty", 
      "SOS Faculty & Researchers", "The Design School", "The Sanford School", 
      "WPC Accountancy", "WPC Economics", "WPC Information Systems", 
      "WPC Management", "WPC Supply Chain Management")



for( i in academic.units )
{

  d2 <- filter( d, Department.Description == i )

    salary.table <- create_salary_table(d2)    # create the salary summary by rank & gender table
top_five <- get_top_five(d2)   # create the top 5 salaries table
      build_graph(salary.table,unit = i)   # build the graph
  # print the tables:
   cat( paste('<h3>',"TOP FIVE SALARIES",'</h3>' ) )
   cat( top_five %>% knitr::kable(format="html") )

   cat( '<br><hr><br>' )

}


```

Now, I am able to build the graphs appropriately - but when I render, I notice that my tables are not sorted by department. I suspect it has to do with my top_five function.

**Comment by DrKBoucher** [comment]
I am having problems with Part II as well. I have to take the academic.units <- out of the function brackets in order for the loops to work.

**Comment by lecy** [comment]
> Now, I am able to build the graphs appropriately - but when I render, I notice that my tables are not sorted by department. I suspect it has to do with my top_five function.

The top_five() function did not require department as an argument, so the department filtering would occur outside of the function. It could look something like this: 

```r
d %>%  
  dplyr::filter( Department.Description == "Psychology" ) %>%   # all people in psychology department
  top_five( ) %>%                                     # create table, but return full psychology data frame
  create_salary_table( ) %>%                  # return salary table only 
  build_graph( unit="Psychology" )     
```

You just need to make sure that the return value from each function matches the type of data needed for the next function. 

Otherwise you don't have to chain everything together if it is impossible to get the object types to align. You can run steps separately since you are just printing results from the first section and not changing the df (there is no assignment happening after you call top_five): 

```r
d %>%  
  dplyr::filter( Department.Description == "Psychology" ) %>%   
  top_five( )  

d %>%  
  dplyr::filter( Department.Description == "Psychology" ) %>%                                    
  create_salary_table( ) %>%                  
  build_graph( unit="Psychology" )     
```

**Comment by lecy** [comment]
> I am having problems with Part II as well. I have to take the academic.units <- out of the function brackets in step 7 in order for the loops to work. If I take the units out of the function, it is recognized in Part II.

That makes sense according to the rules of function scope. If you define an object inside a function it will stay inside the function. The only way to get it out would be as a return value. 

To reference **academic.units** in the loop you would need to load that vector somewhere. 

```r
for( i in academic.units )   # correct way to iterate through units
```

Note that it is already a part of the utils.R file. As long as you are sourcing utils.R at the start of your script then **academic.units** should already be loaded in memory for you and it should work in the loop.
