### ISSUE TITLE
Part III

### ISSUE THREAD

**Issue by DrKBoucher** [Watts-College/paf-514-template#32]
I am now having issues at the beginning of Part III. 

If I do **not** include the code:

URL <- 'https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv'
d <- read.csv( URL )

in the utils.R file, I get this error when running source( 'utils.R' ) within the salary-report.rmd:

Error in nrow(d) : object 'd' not found
(It traces back to line 25 and 49 in the utils.R file where (d) is entered)

If I **do** include the URL code in the utils.R file, I get this error when running the URL <- params$url d <- read.csv( URL ) code in the salary-report.rmd:

Error in file(file, "rt") : cannot open the connection

I am not sure how to solve this to proceed.

**Comment by lecy** [comment]
You are likely trying to preview data or execute functions inside of your utils file. It should be restricted to defining functions or data objects.

It’s hard to give you a better answer unless you share the code at lines 25-49.

**Comment by DrKBoucher** [comment]
I have not executed any functions in the utils.R file. 

Line 25 is the portion where the titles are added using grepl.
add_titles <- function(Job.Description) {
  title <- rep("", nrow(d))

Lines 46-49 are the completion of that function:

  d$title <- factor(title, levels = c("Full Professor", "Associate Professor", "Assistant Professor", "Teaching Faculty", "Researcher"))
  return(title)}

d$title <- add_titles(Job.Description)


My salary-report RMD looks like this:

---
title: "ASU Salary Report"
output:
  html_document:
    theme: readable
    highlight: zenburn
    toc: true
params:
  url:
    value: x   
---

```{r load-packages, include=FALSE}
library( dplyr )
library( pander )
library( knitr )
library( remotes )
library( humaniformat )
library( gender )
library( genderdata )
library( stringr )

source( 'utils.R' )
```

```{r}
URL <- params$url
d <- read.csv( URL )
```

**Comment by lecy** [comment]
I suspect this line:

```r
d$title <- add_titles(Job.Description)
```

**Comment by lecy** [comment]
If that is outside of your function

**Comment by lecy** [comment]
Also the commentary on functions from yesterday. If you are referencing d inside the function it should be passed to the function as an argument.

```r
add_titles <- function(Job.Description) {
title <- rep("", nrow(d))
```

Similarly, you can move that last line where you assign title back to d inside the function and return d instead of returning title.
