### ISSUE TITLE
LAB-01: Question 4

### ISSUE THREAD

**Issue by Mazhar3204** [Watts-College/paf-514-template#34]
Hi Professor, 

For question 4, are we supposed to do a switch loop? 

```{r}
change_door <- function( stay=T, opened.door, a.pick )
{
   doors <- c(1,2,3) 
   
   if( stay )
   {
     final.pick <- a.pick
   }
   if( ! stay )
   {
     final.pick <- doors[ a.pick = switch("car", "goat")] 
   }
  
   return( final.pick ) 
}
```

**Comment by Mazhar3204** [comment]
@lecy 
I am sorry if I posted this wrong; it is my first time posting here.

**Comment by lecy** [comment]
You don’t need to use switch. But you do need to use a logical expression to eliminate the doors you would not select.

Note that if you have selected the car door then you would need to randomly pick one of the goat doors when switching since there is more than one option.

**Comment by lecy** [comment]
Example of a compound logical statement:

```r
# should be 1
game <- c( "goat", "car", "goat" )  
a.pick <- 3   
doors <- 1:3
criteria.1 <- game != "car"
criteria.2 <- doors != a.pick
selector <- criteria.1 & criteria.2
opened.door <- doors[ selector ]
opened.door
[1] 1  
```

**Comment by Mazhar3204** [comment]
Oh ok, that makes sense. So, eliminate the door and the selection when they switch?

**Comment by lecy** [comment]
You can use sample() if there’s more than one remaining.

**Comment by jasminacosta** [comment]
@lecy Hi Professor! 

I am stuck on question #4 as well. Not sure why in my else statement when it randomizes it is only producing the values 1 and 3 for the final.pick.


```{r}

# describe your logic here 




# door to car cannot be chosen
condition1 <- game != "car"

# door initially chosen cannot be selected again
condition2 <- doors != a.pick

# car door not opened and cannot be the same door chosen
door.options <- c(condition1 & condition2)

# makes logical numeric 
potential.options <- doors[door.options]

# randomizes the door chosen (1 DOOR) 

opened.door <- sample(potential.options, size=1)





change_door <- function(stay = T, opened.door, a.pick) {
  
  if (stay) {
    
    final.pick <- a.pick
  } 
  
  else {
    
    final.pick <- sample(potential.options, size = 1)
  }
  return(final.pick)
}


opened.door <- open_goat_door( this.game, my.initial.pick )

change_door( stay=T, 
             opened.door=opened.door, 
             a.pick=my.initial.pick )
change_door( stay=F, 
             opened.door=opened.door, 
             a.pick=my.initial.pick )

my.final.pick <- change_door( stay=F, 
                              opened.door=opened.door, 
                              a.pick=my.initial.pick )

this.game <- create_game()
this.game

my.initial.pick <- select_door()
my.initial.pick

my.final.pick 

```

**Comment by jasminacosta** [comment]
@lecy I think I fixed the issue, but I am not sure. It is returning the different number of doors, but I want to make sure I am going down the right path. 

# door to car cannot be chosen
condition1 <- game != "car"

# door initially chosen cannot be selected again
condition2 <- doors != a.pick

# car door not opened and cannot be the same door chosen
door.options <- c(condition1 & condition2)

# makes logical numeric 
potential.options <- doors[door.options]

# randomizes the door chosen (1 DOOR) 

opened.door <- sample(potential.options, size=1)





change_door <- function(stay = T, opened.door, a.pick) {
  
  if (stay) {
    
    final.pick <- a.pick
  } 
  
  else {
    
    final.pick <- sample(opened.door, size = 1)
  }
  return(final.pick)
}




opened.door <- open_goat_door( this.game, my.initial.pick )

change_door( stay=T, 
             opened.door=opened.door, 
             a.pick=my.initial.pick )
change_door( stay=F, 
             opened.door=opened.door, 
             a.pick=my.initial.pick )

my.final.pick <- change_door( stay=F, 
                              opened.door=opened.door, 
                              a.pick=my.initial.pick )

this.game <- create_game()
this.game

my.initial.pick <- select_door()
my.initial.pick

my.final.pick 

```

**Comment by lecy** [comment]
Let's look at your change_door() function. A couple of things to note.

First, R is pretty flexible with regards to spaces and returns. For the most part it just ignores them.

The if-else constructs are an exception. The else statement needs to be on the same line as the end of the if statement, or you will get an error. I'm breaking open the function here to demonstrate. 
 
```r
game <- c("goat","car","goat")
a.pick <- 1
opened.door <- 3 
stay <- TRUE
  
  if (stay) {
    final.pick <- a.pick
  } 
  
  else {
    # change door here
  }

> Error: unexpected 'else' in "  else"
```

It should be written as: 

```r
stay <- TRUE
  
  if (stay) {
    final.pick <- a.pick
  } else {
    # change door here
  }

final.pick
[1] 1
```
In general I try to avoid if-else constructs when possible. You can just use two if conditions: 

```r
if(stay) {
  final.pick <- a.pick
} 

if( ! stay ) {
  # change door here
}
```

The reason is that if-else uses blunt logic that can make it hard to catch errors in your code. For example, if comparisons are sensitive the if-else version could provide wrong answers in a lot of cases: 

```r
state <- "New York"
if( state == "New York )
{ return unique New York pricing } else 
{ return regular pricing }

# will return false even though 
# it meets the condition but
# the input data is not standardized

state <- "NY"
if( state == "New York )  
{ return unique New York pricing } else 
{ return regular pricing }
```

Or if you have a bug in your code: 

```r
game <- c("goat","car","goat")
a.pick <- 2

# a.pick == "car"
# should actually be:  
# game[a.pick] == "car"

if( a.pick == "car" )  
# { assign final.pick }
if( a.pick == "goat" )
# { assign final.pick }
```

With this double-if version you would see that something is wrong with your code because **final.pick** would never be assigned (you would get an error when you tried to return it). Thus it helps you spot your errors. With the if-else formulation it would return a result that would be incorrect 1/3 of the time, which could be hard to spot. 

This is really splitting hairs here, but an example where both versions work when data is clean and code is correct, but one will be more robust when data is not clean or standardized, and easier to debug.

**Comment by lecy** [comment]
The second issue I see here is the logic behind your switch door option: 

```r
if( stay == FALSE )
    final.pick <- sample( opened.door, size = 1 )
  }
```
I would just walk through your logic. The business rules for switching should be something like: 

1. can't be the current selection 
2. can't be the opened goat door 

If you eliminate those two options would you ever have more than one left?

**Comment by jasminacosta** [comment]
> The second issue I see here is the logic behind your switch door option:
> 
> ```r
> if( stay == FALSE )
>     final.pick <- sample( opened.door, size = 1 )
>   }
> ```
> 
> I would just walk through your logic. The business rules for switching should be something like:
> 
> 1. can't be the current selection
> 2. can't be the opened goat door
> 
> If you eliminate those two options would you ever have more than one left?

In that case there would only be 1 option to open the other goat door, right?

**Comment by lecy** [comment]
This is the change_door() function, not the open_goat_door() function. The logic is similar in both cases, but distinct. 

open_goat_door()

1. can't be the current selection 
2. can't be the car

change_door()

1. can't be the current selection 
2. can't be the opened door

**Comment by jasminacosta** [comment]
@lecy For change door we are focusing on the functions not being a.pick (initial pick) and then we need to create an object where we switch to a door that is not our initial pick and not the opened door?

**Comment by lecy** [comment]
The change_door() function offers an argument that allows the contestant to stay or switch. Your initial formulation was almost correct: 

```r
change_door <- function(stay = T, opened.door, a.pick) {
  if (stay) {
    final.pick <- a.pick
  } 
  if( ! stay ) {
    final.pick <- sample(opened.door, size = 1)
  }
  return(final.pick)
}
```

But you need to apply consistent logic for selecting a door when you decide to switch. This is not correct: 

```r
  if( ! stay ) {
    final.pick <- sample(opened.door, size = 1)
  }
```

The game rules would only allow the contestant to select the other door that has not been opened yet if they want to switch doors.
