### ISSUE TITLE
Lab2- Questions

### ISSUE THREAD

**Issue by acampbell7** [Watts-College/paf-514-template#35]
Hi. I am starting lab two and just put in the initial code you provided I am receiving the error:

Error in if (game[final.pick] == "car") { : the condition has length > 1
2.
determine_winner(final.pick.switch, new.game)
1.
play_game()

warning :Warning: longer object length is not a multiple of shorter object lengthError in if (game[final.pick] == "car") { : the condition has length > 1

I dont know exactly what I did wrong, any guidance would be appreciated. My previous (lab1) code all worked :)

**Comment by lecy** [comment]
I'm confused, which code did I provide? 

If your code was working you can definitely start there. 

I'll share code with the LAB 01 SOLUTIONS but I send those out after the assignment due date has passed.

**Comment by acampbell7** [comment]
Sorry. I misread something in the instructions. I works with my lab one code.  :) I over read too fast.

**Comment by lecy** [comment]
Ok no problem!

**Comment by mkfiles1** [comment]
I used the Lab 1 solutions and I am experiencing an error with play game () resulting in "Error in if (stay) { : the condition has length > 1" All I have done is copied the code out of Lab 1 solutions and then started using the code to start Lab 2
play_game <- function( )
{
  new.game <- create_game()
  first.pick <- select_door()
  opened.door <- open_goat_door( new.game, first.pick )
  final.pick.stay <- change_door( stay=T, opened.door, first.pick )
  final.pick.switch <- change_door( stay=F, opened.door, first.pick )
  outcome.stay <- determine_winner( final.pick.stay, new.game  )
  outcome.switch <- determine_winner( final.pick.switch, new.game )
  
  # game.results <- bundle the results
  # return( <<< game.results >>> )
  
  strategy <- c("stay","switch")
  outcome <- c(outcome.stay,outcome.switch)
  game.results <- data.frame( strategy, outcome,
                              stringsAsFactors=F )
  return( game.results )
}
play_game()
