### ISSUE TITLE
LAB-03: Last Word Function Incorrect Splitting 

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-514-template#40]
@lecy Hi! 

As I am doing Lab 3 and running my function to get the last word from every title I am coming across the issue of the words not splitting correctly, and I am not sure why. 

```{r}

results <- NULL

for (i in 1:length(how.to.score$title)) {
  lower.case <- tolower(how.to.score$title) #lower case 
  word.list <- strsplit(lower.case[i], " " ) # splitting titles 
  word.split <- unlist(word.list) # unlisting 
  word.vector <- gsub("[[:punct:]0-9]", "", word.split) # removing punctuation and numbers 
  results[i] <- tail(word.vector, 1) # retrieving last word 
}

results

```
<img width="134" alt="Screenshot 2024-01-27 at 10 21 42 AM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/1179a4c1-8330-4a6d-bdf0-bf50d1dcbd52">

**Comment by lecy** [comment]
This is a great opportunity to walk through an example of how to debug your code, and also a great example of diagnosing character encoding problems when working with text as data.

## Re-Organized Example

I'm going to start by re-writing the example so it is organized by parts - this will let us see where the problem occurs. 

I'll also include a small sample of titles to [make the example reproducible](https://github.com/Watts-College/paf-514-template/issues/42#issue-2103839209). 

Creating test data (a vector with 10 titles): 

```r
URL <- "https://raw.githubusercontent.com/DS4PS/cpp-527-fall-2020/master/labs/data/medium-data-utf8-v2.csv"
d <- read.csv( URL )
TITLE <- head( d$title, 10 )
dput(TITLE)
c("A Beginner’s Guide to Word Embedding with Gensim Word2Vec Model", 
"Hands-on Graph Neural Networks with PyTorch & PyTorch Geometric", 
"How to Use ggplot2 in Python", "Databricks: How to Save Files in CSV on Your Local Computer", 
"A Step-by-Step Implementation of Gradient Descent and Backpropagation", 
"An Easy Introduction to SQL for Data Scientists", "Hypothesis testing visualized", 
"Introduction to Latent Matrix Factorization Recommender Systems", 
"Which 2020 Candidate is the Best at Twitter?", "What if AI model understanding were easy?"
)
```

Separate into pro-processing steps (outside the loop) and string split steps (inside the loop) so we can isolate the code that is causing the problem. 

```r

TITLE <- 
c("A Beginner’s Guide to Word Embedding with Gensim Word2Vec Model", 
"Hands-on Graph Neural Networks with PyTorch & PyTorch Geometric", 
"How to Use ggplot2 in Python", "Databricks: How to Save Files in CSV on Your Local Computer", 
"A Step-by-Step Implementation of Gradient Descent and Backpropagation", 
"An Easy Introduction to SQL for Data Scientists", "Hypothesis testing visualized", 
"Introduction to Latent Matrix Factorization Recommender Systems", 
"Which 2020 Candidate is the Best at Twitter?", "What if AI model understanding were easy?"
)

### PRO-PROCESSING STEPS 

title <- tolower( TITLE )
title <- gsub( "\\s", "_", title ) 
title <- gsub( "[[:punct:]0-9]", "", title )
head( title, 3 )

 [1] "a beginners guide to word embedding with gensim wordvec model"      
 [2] "handson graph neural networks with pytorch  pytorch geometric"      
 [3] "how to use ggplot in python"

### SPLITTING STRINGS INTO WORDS 

word.list <- strsplit( title, " " ) # splitting titles
head( word.list, 3 )

[[1]]
[1] "a"             "beginners"     "guide"         "to"           
[5] "word"          "embedding"     "with"          "gensim"       
[9] "wordvec model"

[[2]]
[1] "handson"   "graph"     "neural"    "networks"  "with"      "pytorch"  
[7] ""          "pytorch"   "geometric"

[[3]]
[1] "how"       "to"        "use"       "ggplot"    "in python"

### SELECTING THE LAST WORD  

results <- NULL

for (i in 1:length(word.list) ) 
{
  word.vec    <- unlist( word.list[[i]] )    # unlisting 
  results[i]  <- tail( word.vec, 1 )         # retrieving last word 
}

results
 [1] "wordvec model"   "geometric"       "in python"       "local computer" 
 [5] "backpropagation" "scientists"      "visualized"      "systems"        
 [9] "at twitter"      "were easy"
```

We can see that some cases look fine. "An Easy Introduction to SQL for Data Scientists" returns "scientists", for example. 

For others, though, we get two words instead of one: 

```
"wordvec model"   "geometric"       "in python"       "local computer" 
```

## Double-Check the Code  

First, let's break open the loop to ensure it's a data problem and not a code problem: 

```r
# running loop steps outside of the loop

results <- NULL

i <- 1
word.vec    <- unlist( word.list[[i]] )
word.vec

[1] "a"             "beginners"     "guide"         "to"           
[5] "word"          "embedding"     "with"          "gensim"       
[9] "wordvec model"

results[i]  <- tail( word.vec, 1 )           
results

[1] "wordvec model"
```

Ok, it looks like a data problem. 

## Inspect the Data

This one is a bit tricky to diagnose, so I did a few things. I copied the space between the words above and tested some functions to confirm it's not a regular space and see if I can resolve it. 

```r
> " " == " "
[1] FALSE

x1 <- "real space"
x2 <- "fake space"

gsub( "[[:space:]]", "__", x1 )
[1] "real__space"

gsub( "[[:space:]]", "__", x2 )
[1] "fake space"

gsub( "\\s", "__", x2 )
[1] "fake space"
```

The typical regex space operators are not able to identify this particular kind of space. I had to resort to some base R primitive functions for working with characters to see what is happening here. Specifically, I will examine a string with one real space and one fake space: 

```r
x <- "x x x"

gsub( " ", "__", x )  # make sure one is the fake space
[1] "x x__x"

charToRaw(x)  # converts strings to UTF-8 encoding
[1] 78 c2 a0 78 20 78
```

I can see here that **x** is converted to **78**, space is converted to **20**, and the fake space is converted to **c2 a0**. 

Now I can search for this special character on Google, and I will find lots of sites like this: 

https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=302+240&mode=obytes

It tells me that in the UTF-8 encoding system this character is called a NO-BREAK SPACE. Searching for a non-breaking space I will find: 

> Text-processing software typically assumes that an automatic line break may be inserted anywhere a space character occurs; a non-breaking space prevents this from happening (provided the software recognizes the character). For example, if the text "100 km" will not quite fit at the end of a line, the software may insert a line break between "100" and "km". A non-breaking space guarantees that the text "100 km" will not be broken: if it does not fit at the end of a line, it is moved in its entirety to the next line.

So it is a special type of space that is used to ensure two words that belong together are not split apart by word processors. In this case it looks like Medium was using these spaces with the last two words in titles to ensure that HTML browsers were not creating a single trailing word in the title. 

## The Fix 

Once we have this information the fix is pretty easy. We can add a pre-processing step that replaces all non-breaking spaces with regular spaces. 

```r
x <- "x x x"  # test case with both types

gsub( "[ ]", "__", x )  # regular space
[1] "x x__x"

gsub( "[ ]|[ ]", "__", x )  # try both types
[1] "x__x__x"

gsub( "[ ]", "__", title )  # find and replace for non-breaking spaces 
 [1] "a beginners guide to word embedding with gensim wordvec__model"     
 [2] "handson graph neural networks with pytorch  pytorch geometric"      
 [3] "how to use ggplot in__python" 

strsplit( x, "[ ]|[ ]" )  # this could also work
[[1]]
[1] "x" "x" "x"                                     
```

I would not expect you to know how to address this particular issue - it goes beyond the scope of this initial text-as-data lab. Submitting your original solution would have been fine. 

But I did leave the issue in the lab data as a reminder that working with text can be tricky, and as an opportunity to walk through the process of diagnosing this type of problem. 

This solution is a little pedantic, but it is meant as an example of steps one might take to identify the issue when code is not working as expected.  

Per usual, I care more about the process that you are following than the precise, exact answer. Are you able to break your code into smaller and smaller parts until you have isolated the issue? If you can reproduce an error you can most certainly get help fixing it.

**Comment by jasminacosta** [comment]
> This is a great opportunity to walk through an example of how to debug your code, and also a great example of diagnosing character encoding problems when working with text as data.
> 
> ## Re-Organized Example
> I'm going to start by re-writing the example so it is organized by parts - this will let us see where the problem occurs.
> 
> I'll also include a small sample of titles to [make the example reproducible](https://github.com/Watts-College/paf-514-template/issues/42#issue-2103839209).
> 
> Creating test data (a vector with 10 titles):
> 
> ```r
> URL <- "https://raw.githubusercontent.com/DS4PS/cpp-527-fall-2020/master/labs/data/medium-data-utf8-v2.csv"
> d <- read.csv( URL )
> TITLE <- head( d$title, 10 )
> dput(TITLE)
> c("A Beginner’s Guide to Word Embedding with Gensim Word2Vec Model", 
> "Hands-on Graph Neural Networks with PyTorch & PyTorch Geometric", 
> "How to Use ggplot2 in Python", "Databricks: How to Save Files in CSV on Your Local Computer", 
> "A Step-by-Step Implementation of Gradient Descent and Backpropagation", 
> "An Easy Introduction to SQL for Data Scientists", "Hypothesis testing visualized", 
> "Introduction to Latent Matrix Factorization Recommender Systems", 
> "Which 2020 Candidate is the Best at Twitter?", "What if AI model understanding were easy?"
> )
> ```
> 
> Separate into pro-processing steps (outside the loop) and string split steps (inside the loop) so we can isolate the code that is causing the problem.
> 
> ```r
> TITLE <- 
> c("A Beginner’s Guide to Word Embedding with Gensim Word2Vec Model", 
> "Hands-on Graph Neural Networks with PyTorch & PyTorch Geometric", 
> "How to Use ggplot2 in Python", "Databricks: How to Save Files in CSV on Your Local Computer", 
> "A Step-by-Step Implementation of Gradient Descent and Backpropagation", 
> "An Easy Introduction to SQL for Data Scientists", "Hypothesis testing visualized", 
> "Introduction to Latent Matrix Factorization Recommender Systems", 
> "Which 2020 Candidate is the Best at Twitter?", "What if AI model understanding were easy?"
> )
> 
> ### PRO-PROCESSING STEPS 
> 
> title <- tolower( TITLE )
> title <- gsub( "\\s", "_", title ) 
> title <- gsub( "[[:punct:]0-9]", "", title )
> head( title, 3 )
> 
>  [1] "a beginners guide to word embedding with gensim wordvec model"      
>  [2] "handson graph neural networks with pytorch  pytorch geometric"      
>  [3] "how to use ggplot in python"
> 
> ### SPLITTING STRINGS INTO WORDS 
> 
> word.list <- strsplit( title, " " ) # splitting titles
> head( word.list, 3 )
> 
> [[1]]
> [1] "a"             "beginners"     "guide"         "to"           
> [5] "word"          "embedding"     "with"          "gensim"       
> [9] "wordvec model"
> 
> [[2]]
> [1] "handson"   "graph"     "neural"    "networks"  "with"      "pytorch"  
> [7] ""          "pytorch"   "geometric"
> 
> [[3]]
> [1] "how"       "to"        "use"       "ggplot"    "in python"
> 
> ### SELECTING THE LAST WORD  
> 
> results <- NULL
> 
> for (i in 1:length(word.list) ) 
> {
>   word.vec    <- unlist( word.list[[i]] )    # unlisting 
>   results[i]  <- tail( word.vec, 1 )         # retrieving last word 
> }
> 
> results
>  [1] "wordvec model"   "geometric"       "in python"       "local computer" 
>  [5] "backpropagation" "scientists"      "visualized"      "systems"        
>  [9] "at twitter"      "were easy"
> ```
> 
> We can see that some cases look fine. "An Easy Introduction to SQL for Data Scientists" returns "scientists", for example.
> 
> For others, though, we get two words instead of one:
> 
> ```
> "wordvec model"   "geometric"       "in python"       "local computer" 
> ```
> 
> ## Double-Check the Code
> First, let's break open the loop to ensure it's a data problem and not a code problem:
> 
> ```r
> # running loop steps outside of the loop
> 
> results <- NULL
> 
> i <- 1
> word.vec    <- unlist( word.list[[i]] )
> word.vec
> 
> [1] "a"             "beginners"     "guide"         "to"           
> [5] "word"          "embedding"     "with"          "gensim"       
> [9] "wordvec model"
> 
> results[i]  <- tail( word.vec, 1 )           
> results
> 
> [1] "wordvec model"
> ```
> 
> Ok, it looks like a data problem. It appears when we first split the title into words, and is not impacted by our code.
> 
> ## Inspect the Data
> This one is a bit tricky to diagnose, so I did a few things. I copied the space between the words above and tested some functions to confirm it's not a regular space and see if I can resolve it.
> 
> ```r
> > " " == " "
> [1] FALSE
> 
> x1 <- "real space"
> x2 <- "fake space"
> 
> gsub( "[[:space:]]", "__", x1 )
> [1] "real__space"
> 
> gsub( "[[:space:]]", "__", x2 )
> [1] "fake space"
> 
> gsub( "\\s", "__", x2 )
> [1] "fake space"
> ```
> 
> The typical regex space operators are not able to identify this particular kind of space. I had to resort to some base R primitive functions for working with characters to see what is happening here. Specifically, I will examine a string with one real space and one fake space:
> 
> ```r
> x <- "x x x"
> 
> gsub( " ", "__", x )  # make sure one is the fake space
> [1] "x x__x"
> 
> charToRaw(x)  # converts strings to UTF-8 encoding
> [1] 78 c2 a0 78 20 78
> ```
> 
> I can see here that **x** is converted to **78**, space is converted to **20**, and the fake space is converted to **c2 a0**.
> 
> Now I can search for this special character on Google, and I will find lots of sites like this:
> 
> https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=302+240&mode=obytes
> 
> It tells me that in the UTF-8 encoding system this character is called a NO-BREAK SPACE. Searching for a non-breaking space I will find:
> 
> > Text-processing software typically assumes that an automatic line break may be inserted anywhere a space character occurs; a non-breaking space prevents this from happening (provided the software recognizes the character). For example, if the text "100 km" will not quite fit at the end of a line, the software may insert a line break between "100" and "km". A non-breaking space guarantees that the text "100 km" will not be broken: if it does not fit at the end of a line, it is moved in its entirety to the next line.
> 
> So it is a special type of space that is used to ensure two words that belong together are not split apart by word processors. In this case it looks like Medium was using these spaces with the last two words in titles to ensure that HTML browsers were not creating a single trailing word in the title.
> 
> ## The Fix
> Once we have this information the fix is pretty easy. We can add a pre-processing step that replaces all non-breaking spaces with regular spaces.
> 
> ```r
> x <- "x x x"  # test case with both types
> 
> # replace space with __ so you can see it
> 
> gsub( "[ ]", "__", x )  # regular space
> [1] "x x__x"
> 
> gsub( "[ ]|[ ]", "__", x )  # try both types
> [1] "x__x__x"
> 
> gsub( "[ ]", "__", title )  # find and replace for non-breaking spaces 
>  [1] "a beginners guide to word embedding with gensim wordvec__model"     
>  [2] "handson graph neural networks with pytorch  pytorch geometric"      
>  [3] "how to use ggplot in__python" 
> 
> # [ ]|[ ]  - regex with both space types separated by OR operator
> 
> strsplit( x, "[ ]|[ ]" )  # this could also work
> [[1]]
> [1] "x" "x" "x"                                     
> ```
> 
> I would not expect you to know how to address this particular issue - it goes beyond the scope of this initial text-as-data lab. Submitting your original solution would have been fine.
> 
> But I did leave the issue in the lab data as a reminder that working with text can be tricky, and as an opportunity to walk through the process of diagnosing this type of problem.
> 
> This solution is a little pedantic, but it is meant as an example of steps one might take to identify the issue when code is not working as expected.
> 
> Per usual, I care more about the process that you are following than the precise, exact answer. Are you able to break your code into smaller and smaller parts until you have isolated the issue? If you can reproduce an error you can most certainly get help fixing it.

@lecy That makes a lot of sense!

I would have never guessed that, will try that out and see what happens. 

In that case if the data is spaced in a particular manner, does that mean when we create our function to retrieve the title length based on the number of words will it not be precise due that spacing? 

Example: "10 Ways to Spice Up a UI Design" 
title length based on number of words from the function = 7
clap score = 3.785401

However, when I count it the number of words within that title should be 8, but the data is seeing "UI Design" as one word. 

Thank you!

**Comment by lecy** [comment]
If you pre-process the text correctly it should give you the correct word count. 

```r
x <- "10 Ways to Spice Up a UI Design"
x %>% strsplit(" ") %>% unlist() %>% length()
[1] 7

x <- gsub( "[ ]", " ", x )
x %>% strsplit(" ") %>% unlist() %>% length()
[1] 8
```

**Comment by Mazhar3204** [comment]
Hi Professor, 
It is usual for the output to be significant. I am getting over 900.
