### ISSUE TITLE
R Package- "R scripts into the “R” folder in your package directory"

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-514-template#43]
@lecy Hi! 

I am having issues with my R package for the Monty Hall package that we are creating. I have my documentation written down and ready to go, but I am having issues with this part of the instructions: 

```{r}
# Instructions Steps

setwd( "montyhall" )
getwd()   # 'C:/Users/username/Documents/montyhall'
devtools::document()
```

When I run getwd() I get this pathway: 

```{r}
getwd() 

[1] "/Users/jasminacosta/montyhall"

```

Then I tried 

```{r}

setwd("C:\Users\jasminacosta\montyhall")
getwd()   
devtools::document()

Error: '\U' used without hex digits in character string (<input>:1:11)

```

Another thing I tried:

```{r}

setwd( "montyhall" )
getwd("C:\Users\jasminacosta\montyhall")
devtools::document()

Error in setwd("montyhall") : cannot change working directory

```

Not sure how to fix this issue since I have my R script in the R folder like how the instructions stated.

**Comment by lecy** [comment]
Note that R uses unix style paths with backslashes while Windows uses forward slashes. 

```r
"\Users\jasminacosta\montyhall"   # windows
"/Users/jasminacosta/montyhall"   # R

setwd( "/Users/jasminacosta/montyhall" )  # this one works
setwd( "\Users\jasminacosta\montyhall" )  # this one doesn't
```

**Comment by Leah-Coffin** [comment]
@lecy 

I am encountering an error when I attempt to set my working directory for the package.

`setwd( "C:/Users/lredbur/montyhall" )
usethis::create_package( "montyhall" )
`
I get this message in the R Console

`Error in setwd("C:/Users/lredbur/montyhall") : 
  cannot change working directory
> usethis::create_package( "montyhall" )
New project 'montyhall' is nested inside an existing project './', which is rarely a good idea.
If this is unexpected, the here package has a function, `here::dr_here()` that reveals why './' is regarded as a project.
Do you want to create anyway?

1: No
2: Absolutely not
3: I agree
`
I set my working directory to the following to see if that would help but I still get the same message.

`> getwd()
[1] "C:/Users/lredbur/Documents/montyhall"`

Should I ignore the error and create anyway or is there a step I'm missing?

**Comment by lecy** [comment]
The warning message occurs because you created a project folder called "montyhall" and are trying to create a package folder called "montyhall" inside of it. 

Specifically when you call `usethis::create_package( "montyhall" )` it will create a new folder called "montyhall" and add the R package skeleton files. 

You can delete your current montyhall folder and then try create_package(). In the end you want something like this: 

```
documents     # package created inside documents 
├─ montyhall  # new folder that will appear after create_package()
│  ├─ R
```

Avoid this: 

```
documents     
├─ montyhall   # package created here
│  ├─ montyhall  # new folder that will appear after create_package()
│       ├─ R
```
