### ISSUE TITLE
R Package Hosting on GitHub Issue

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-514-template#44]
@lecy Hi! 

At first my package was running fine for the monty hall R package, but once I got to sharing my package with GitHub that is where I am now having odd issues.

My pathways was completely changed to something I do not recognize.

```{r}
setwd( "/" )
getwd()   # 'C:/Users/username/Documents/montyhall'
devtools::document()

> getwd() 
[1] "/"
```

Now there is a copy of my monty hall folder in another monty hall folder, and I am having issues moving it outside of that copied folder.

**Comment by lecy** [comment]
You can always delete your GitHub repo and start over. After your package is working you would not be using the document() function anymore. You should just be cloning your GitHub repo, copying the package files into the repo, then pushing to GitHub. 

Did you follow all of the steps using the GitHub desktop app? 


## 1.4.1 Hosting on GitHub

A simpler option is to host your package on GitHub. Complete the following steps to upload your code to a new repository on GitHub:

1. Install the git client on your computer: [LINK](https://git-scm.com/downloads).
1. Install GitHub Desktop application: [LINK](https://desktop.github.com/).
1. Open GitHub in a browser and navigate to your profile.
1. Create a new repository titled “montyhall”. Check the “Create with README” option.
1. Copy the URL for your new repository.
1. Open GitHub desktop and select File >> Clone Repository.
1. Select the desired location of the folder and paste the URL into the appropriate dialogue.
1. Clone your GitHub repo.
1. Open the new “montyhall” folder that was just created by GitHub on your machine.
1. Transfer all of the files inside of your old “montyhall” folder into the GitHub version.
1. You should see the files appear in the GitHub Desktop app. In the “summary” field type something like “initial commit” and at the bottom left select “Commit to master”.
1. Now up at the top select “Push origin”

**Comment by jasminacosta** [comment]
@lecy I deleted the Github Repo and started from scratch with trying to get my package running again, but I am still having issues with the pathways.

I fixed the folders and put everything into the monty hall folder correctly, but now the pathways is acting strange. 

```{r}

setwd( ".." )  # move up one level with two periods
getwd() 

> getwd() 
[1] "/" # new pathway it's giving me? 

```

I had followed the steps and once I selected “Push origin” that is when everything started acting up.

**Comment by lecy** [comment]
Do you have an R project file in your repo?

**Comment by lecy** [comment]
After you have documented your R scripts you can copy the files from that folder into your GitHub version. The directory path should not matter (just click on the files, right-select copy and paste them in your new folder). 

Check if you have this file: 

```
.RProj 
```

That is an R Project file. It is probably the reason your directory is acting weird. It creates a relative path structure - relative to the folder you are currently in. You don't actually need that file for the package, though.

**Comment by jasminacosta** [comment]
@lecy 

This is what I see in my file

<img width="553" alt="Screenshot 2024-02-01 at 9 57 03 AM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/d035a1c5-9573-410c-9092-6a2cbbffc541">

**Comment by lecy** [comment]
The file `montyhall.Rproj` is the one changing your working directory structure. It's not actually changing the file locations - it just uses a relative path structure. The reference point becomes the project folder, not your entire computer.

```
'C:/Users/username/Documents/montyhall/R'  # absolute path
'/R'  # relative path - relative to the starting point (project folder)
```

Either of these would still work: 

```r
setwd( "/R" )
setwd( "C:/Users/username/Documents/montyhall/R" )  
```

You will learn more about this in PAF-515 DS3 Project Management. 

It should not matter once you have successfully documented your package (after running devtools::document() you have .RD files in the /man folder and after you have updated the DESCRIPTION file). At that point you can follow these steps: 

1. Open GitHub in a browser and navigate to your profile.
1. Create a new repository titled “montyhall”. Check the “Create with README” option.
1. Copy the URL for your new repository.
1. Open GitHub desktop and select File >> Clone Repository.
1. Select the desired location of the folder and paste the URL into the appropriate dialogue.
1. Clone your GitHub repo.
1. Open the new “montyhall” folder that was just created by GitHub on your machine.
1. Transfer all of the files inside of your old “montyhall” folder into the GitHub version.

Then just copy and paste the following files into the new **montyhall** folder:

```
DESCRIPTION
NAMESPACE
/R  # entire folder
/man  # entire folder 
```

Those are the only files needed for the package. 

The rest are project management files created by RStudio. They are useful (you will learn in PAF-515), but not needed for this assignment.

**Comment by lecy** [comment]
> Another odd thing as well when I would test the create_game() function it would return 5 doors, 3 goats, and 2 cars when that is no where in my documentation, so I uninstalled it to restart and I am having issues getting it running again.

That would be a code problem, not a documentation problem. What did your function look like in your .R script? Were you using the version that creates different games?

**Comment by jasminacosta** [comment]
> The file `montyhall.Rproj` is the one changing your working directory structure. It's not actually changing the file locations - it just uses a relative path structure. The reference point becomes the project folder, not your entire computer.
> 
> ```
> 'C:/Users/username/Documents/montyhall/R'  # absolute path
> '/R'  # relative path - relative to the starting point (project folder)
> ```
> 
> Either of these would still work:
> 
> ```r
> setwd( "/R" )
> setwd( "C:/Users/username/Documents/montyhall/R" )  
> ```
> 
> You will learn more about this in PAF-515 DS3 Project Management.
> 
> It should not matter once you have successfully documented your package (after running devtools::document() you have .RD files in the /man folder and after you have updated the DESCRIPTION file). At that point you can follow these steps:
> 
> 1. Open GitHub in a browser and navigate to your profile.
> 2. Create a new repository titled “montyhall”. Check the “Create with README” option.
> 3. Copy the URL for your new repository.
> 4. Open GitHub desktop and select File >> Clone Repository.
> 5. Select the desired location of the folder and paste the URL into the appropriate dialogue.
> 6. Clone your GitHub repo.
> 7. Open the new “montyhall” folder that was just created by GitHub on your machine.
> 8. Transfer all of the files inside of your old “montyhall” folder into the GitHub version.
> 
> Then just copy and paste the following files into the new **montyhall** folder:
> 
> ```
> DESCRIPTION
> NAMESPACE
> /R  # entire folder
> /man  # entire folder 
> ```
> 
> Those are the only files needed for the package.
> 
> The rest are project management files created by RStudio. They are useful (you will learn in PAF-515), but not needed for this assignment.

@lecy I have documented everything and the pathways given is giving the error:

```{r}

setwd( "C:/Users/jasminacosta/Documents/montyhall/R" )  # move up one level with two periods
getwd()        # should be /documents NOT /montyhall 
devtools::install( "montyhall" )

setwd( "/R" )  # move up one level with two periods
getwd()        # should be /documents NOT /montyhall 
devtools::install( "montyhall" )

Error in setwd("C:/Users/jasminacosta/Documents/montyhall/R") : 
  cannot change working directory

Error in setwd("/R") : cannot change working directory

```

I had uninstalled the package, but I am unable to download the package now.

**Comment by jasminacosta** [comment]
> /R

@lecy 

I tried checking, but since I installed it and can't download it again I am having trouble seeing the issue on why that was occurring.
