### ISSUE TITLE
LAB-03: R not recognizing hair space

### ISSUE THREAD

**Issue by emileeich** [Watts-College/paf-514-template#45]
In the text pre-processing state when working to remove the fake spaces in the titles, I have been unable to define the u200A hairspace. 

In my code below, I have been able to successfully identify which spaces are hairspaces vs. regular spaces. But when I copy the "hairspace" into R to replace, it shows up as a red box with a white period (I attached a screenshot of this). It is also not removing or replacing the hairspace when I run that line. 

```
library( pander )
library( dplyr )

URL <- "https://raw.githubusercontent.com/DS4PS/cpp-527-fall-2020/master/labs/data/medium-data-utf8-v2.csv"
data <- read.csv( URL )

#remove html tags
data$title <- gsub("<.*?>", "", data$title)
head(data$title, 50)

#identify hair spaces by replacing with dash marks
iconv(data$title, "UTF-8", "ASCII", sub="_")
head(data$title, 50)

#remove strange spaces and hair space dash marks
data$title <- gsub( "[ ]", "", data$title )
head(data$title, 50)

iconv(data$title, "UTF-8", "ASCII", sub="_")
head(data$title, 50)

[  U+200A HAIR SPACE](https://unicode-explorer.com/c/200A)
```

![Screenshot 2024-01-31 125402](https://github.com/Watts-College/paf-514-template/assets/95936326/4b1b40eb-48ff-45c3-96e7-f11b315623e3)

**Comment by lecy** [comment]
This should be sufficient except you need to replace the hairspace with a regular space.

```r
data$title <- gsub( "[ ]", " ", data$title )
```

The other cases are instances where the hairspace is represented by an html tag. If you implemented your code to remove tags correctly then it will take care of those as well. 

The red dot you see is just formatting used by RStudio to make the irregular space visible to programmers.

**Comment by lecy** [comment]
I would grab an example of a title with HTML tags and test this. I don’t think it’s doing what you believe it is.

```r
#remove html tags
data$title <- gsub("<.*?>", "", data$title)
```

**Comment by lecy** [comment]
Ignore the last comment. I stand corrected - it does work: 

```r
x <- "<strong class=\'markup--strong markup--h3-strong\'>Tackle Negative Core Beliefs</strong>"
gsub( "<.*?>", "", x )
[1] "Tackle Negative Core Beliefs"
```
