### ISSUE TITLE
Lab 04 - Part 1

### ISSUE THREAD

**Issue by Mazhar3204** [Watts-College/paf-514-template#46]
@lecy 

Hi Professor, 

I am unsure how you look for blanks or spaces for question 2. 

```r
grepl( dat$mission != "", dat$mission, ignore.case=TRUE)
```

I was trying this to search for blanks.

**Comment by lecy** [comment]
I would always start by creating an example for yourself where you know what the answers should be in order to test your solutions. 

```r
x <- 
  c( "abc", 
     "a b c", 
     " abc ", 
     "",       # blank
     " ",      # 1 space
     "  ",     # 2 spaces
     "   " )   # 3 spaces

grepl( "", x )  # doesn't work - identifies everything
[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE

grepl( "^$", x )  # use anchors to limit the scope
[1] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE

grepl( " ", x )   # what's happening here? 
[1] FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
```

**Comment by Mazhar3204** [comment]
> I would always start by creating an example for yourself where you know what the answers should be in order to test your solutions.
> 
> ```r
> x <- 
>   c( "abc", 
>      "a b c", 
>      " abc ", 
>      "",       # blank
>      " ",      # 1 space
>      "  ",     # 2 spaces
>      "   " )   # 3 spaces
> 
> grepl( "", x )  # doesn't work - identifies everything
> [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> 
> grepl( "^$", x )  # use anchors to limit the scope
> [1] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
> 
> grepl( " ", x )   # what's happening here? 
> [1] FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
> ```

**Comment by lecy** [comment]
> It pulls all the blanks, right?

```r
grep( pattern="^$", x=dat$mission, value=TRUE )
```

Correct, `grep( value=TRUE )` will return the set of cases that match the pattern. If you want to count the cases that match a pattern, though, the logical vectors are easier.

```r
grepl( … ) %>% sum()
```
