### ISSUE TITLE
Lab #5 Step 4- new div sections around Step 02 and Step 03 on the page

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-514-template#48]
Hi @lecy!

On Step #4 I am still having difficulty understanding how to add the new div sections around Step 02 and Step 03 on the page. 

On the instructions of Step 4 it states to:

"Make sure your file is a markdown .md file type and not an HTML .html file.
Either will work with GitHub pages, but only the .md files are automatically converted from MD to HTML on the GitHub (kramdown) servers. If you add markdown elements to an HTML file type they will not be converted." 

On Step #2: it is a _config.yml file so I tried adding div tags as is, but it did not work. I tried coverting it to a md. file, but that did not work as intended.

Then on Step #3: it is a README.md that holds the CSS style sheet that we created for Step #4, but on the instructions I see on step #3 there is a index.html file that holds 

```{r}
---
layout: page
title: My website
subtitle: This is where I will tell my friends way too much about me
use-site-title: true
---
```

However, I am unable to add div tags since it is an HTML file and not a md. file 

On the flip side I was able to change sytlyistic elements to different aspects of my website without the div tags.

I am just having an issue understanding how to add div tags to those files when they are not md files. 

I attached some stylistic changes I made to the website. 

Thank you!

<img width="1316" alt="Screenshot 2024-02-06 at 10 44 50 AM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/1d6f7751-836a-4940-89c8-65085faae88c">

<img width="1047" alt="Screenshot 2024-02-06 at 10 45 57 AM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/37fb58e2-d98b-45f3-83a1-8199fd93fb4c">

<img width="864" alt="Screenshot 2024-02-06 at 10 46 29 AM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/866913b7-4b8c-4176-977c-914afedca820">

**Comment by lecy** [comment]
The instructions are referring to the Step 1 - Step 3 text on the instructions page, not the prior Step 02 and Step 03 in the lab. 

You are creating a unique divider tag (different classes) for each step. In other words, there should be a noticeable difference in the formatting of the sections (font, font size, font color, etc.).

## First Section: class="gs-section-01"

```
<div class="gs-section-01" markdown="1">
### 1. Fork the Beautiful Jekyll repository
...
</div>
```

## Second Section: class="gs-section-02"

```
<div class="gs-section-02" markdown="1">
### 2. Build your website in 3 steps
...
</div>
```

## Section Rules in CSS Using Tag Classes:



```
# only <h3> headers between <div class=gs-section-01> tags
.gs-section-01 h3 { 
   color: red
}

# only <h3> headers between <div class=gs-section-02> tags
.gs-section-02 h3 { 
   color: blue
}
```
