### ISSUE TITLE
Lab 04 - Part 2

### ISSUE THREAD

**Issue by Mazhar3204** [Watts-College/paf-514-template#49]
I am looking at the example in part 2, and it mentions that it is one single concept. Does that mean we need to do that process 10 times or just include 10 different functions, such as making the words capital, making the words a minimum amount, and losing punctuation? Would that be considered adding three concepts to the dictionary? 

@lecy

**Comment by lecy** [comment]
Lab 04, right? If you are asking about applying the dictionary, you just need to add ten concepts (word or phrase variant that maps onto a canonical version).

```r
my_dictionary <- dictionary( list( five01_c_3= c("501 c 3","section 501 c 3") ,
                             united_states = c("united states"),
                             high_school=c("high school"),
                             non_profit=c("non-profit", "non profit"),
                             stem=c("science technology engineering math", 
                                    "science technology engineering mathematics" ),
                             los_angeles=c("los angeles"),
                             ny_state=c("new york state"),
                             ny=c("new york")
                           ))

```
