### ISSUE TITLE
Formatting for Inspection

### ISSUE THREAD

**Issue by tbnaes** [Watts-College/paf-514-template#5]
Hi class, 

I made it to the final section, even ran 5 successful unit tests, but every time I try to knit with this last section included in the code I get Execution Halted. RStudio says there's a line 404 problem, however, the error only occurs when I include the section starting at line 420. Am I missing a vital package to knit this last section? How did you get this final section to knit properly?

![lab1screen](https://github.com/Watts-College/paf-514-template/assets/118477975/4e2d5f3c-f2cc-47a3-87ac-5118e84d0e97)

**Comment by lecy** [comment]
I can’t see any of your game functions so I can’t diagnose what might be going wrong without you sharing some output from the game functions. But I suspect that is where you are hitting problems.

you can rest the chunk of code starting at 420 by hard-coding game values inside the chunk and testing that way. 

```r
this.game <- c(“goat”,”car”,”goat”,”goat”,”goat”)
my.initial.pick <- 4
# etc
```

Otherwise add some print statements of your game object so we can see what your updated code for Part 2 produces.

**Comment by tbnaes** [comment]
By part 2 do you mean Challenge Questions, Part 2? I worked out of order and got the unit tests to work, then put time into that final section. I used your hard code idea and that worked, so I dug in a bit further to find where my code wasn't lining up. The given code for that final section asks for several objects from the game code, but with different naming. I found where I had not aligned the naming perfectly and fixed it. 

From part 5 (test) of the original game:
```
my.final.pick.switch <- change_door( stay=F, 
                                     opened.door=opened.door, 
                                     a.pick=my.initial.pick )

game.outcome.switch <- determine_winner( final.pick=my.final.pick.switch, 
                                         game=this.game )

game.outcome.switch
```
Now I can make a knit file with no issues. Thanks for the idea of hard coding into that inline code section.
I may make it to the challenge questions 1 and 2 by Friday. Truthfully, I wasn't sure if the 'unit test / formatting for inspection' were meant as part of the original lab so I went ahead and worked through them.

**Comment by gmendez9** [comment]
Hi all -

I am working through questions 4 and 5, and I want to ensure my code for #4 is proper, as I am unsure if it is related to the following error message when looking to inspect the code : Error in if (game[final.pick] == "car") { : the condition has length > 1



change_door <-  function( stay=T, opened.door, a.pick )
{

   if( stay==TRUE )
   { final.pick <-  a.pick }

   if( stay==FALSE )
   { final.pick <- my.initial.pick     }

   return( final.pick )  # number between 1 and 3

}
