### ISSUE TITLE
final project- trouble downloading the needed files 

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-514-template#51]
Hi @lecy! 

I wanted to get a head start on the final project and it seems like I cannot download the files needed. 

Please let me know how to proceed.

Thank you! 

<img width="1175" alt="Screenshot 2024-02-09 at 6 23 20 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/c76e1852-5f57-426c-9417-77f00ac65f61">
<img width="797" alt="Screenshot 2024-02-09 at 6 23 34 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/c2ce1987-2bca-4542-bbbd-d9992178a70d">
<img width="660" alt="Screenshot 2024-02-09 at 6 23 53 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/1e8db735-1c56-43c8-8b1e-27eb2740a71d">

**Comment by jasminacosta** [comment]
@lecy Never mind I was able to open it through the course website, thank you!

**Comment by lecy** [comment]
I'm not sure what's going on with the Canvas links. The github site will generally be the safer bet.

**Comment by jasminacosta** [comment]
@lecy Got it, thank you! Not sure if you saw my other question but I am just having issues getting the actual files to run before I start the final project instructions despite downloading Pandoc and updating Rmarkdown.
