### ISSUE TITLE
Final Project- Setting up the files

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-514-template#52]
Hi @lecy! 

Before starting the final project steps I am having issues loading the files to make sure they work correctly. 

Note: I did download Pandoc and update the Rmarkdown package.

<img width="1230" alt="Screenshot 2024-02-09 at 7 09 01 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/5cef0b8b-6453-48f1-9bc4-19b7dfb3f00b">

<img width="645" alt="Screenshot 2024-02-09 at 7 09 31 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/80424ccd-835b-42b5-93f2-6bd41d09fc95">

<img width="630" alt="Screenshot 2024-02-09 at 7 10 10 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/dee53a2a-2c49-45ef-b52e-2df4167c3aca">

**Comment by jasminacosta** [comment]
@lecy I added the yaml header but it is still not running the RMD doc. 

<img width="637" alt="Screenshot 2024-02-11 at 5 46 33 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/0c0d737d-5353-4417-aed3-00e855ac9906">

**Comment by lecy** [comment]
I ran it today and it worked so I know the code is ok.

Try it again. Might be a bad connection.

You can test the data load step like this:

```r
url.2020 <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
d <- read.csv( url.2020 )
```

**Comment by jasminacosta** [comment]
I tried the following code provided and it did run properly.

Should I replace this part of the code and replace it with the new code provided? 

```{r}

# LOAD DATA 
URL <- params$url         #replace this part of the code 
d <- read.csv( URL )

```
Replace with the following code:

```{r}

url.2020 <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
d <- read.csv( url.2020 )        #use this part of code instead?

```

**Comment by lecy** [comment]
For testing purposes that's fine. If you replace the current code in the RMD doc, though, you are hard-coding a single year of data into your RMD template, and it can no longer be used as part of a batch process to create reports across multiple years. 

You don't actually knit the RMD file in this case. It is a template that you execute through the batch file: 

```r
# utils.R and salary-report.rmd should be in the working directory

## 2020 REPORT
url.2020 <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
rmarkdown::render( input='salary-report.rmd', 
                   output_file = "ASU-2020-Salary-Report.HTML",
                   params = list( url = url.2020 ) )
```

It will make more sense after you finish Lab-06 and use the Resume template.

**Comment by jasminacosta** [comment]
@lecy So is it fine for me to start working on? Despite these errors popping up?

**Comment by lecy** [comment]
You shouldn't be getting errors if you are running it correctly.

My question is whether you are executing as described in the assignment? 

> "Before you go on to next steps, download these three files do your local working directory. Open batch.R in a regular R console and try running the reports to create the HTML files."

```r
# utils.R and salary-report.rmd should be in the working directory

## 2020 REPORT
url.2020 <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
rmarkdown::render( input='salary-report.rmd', 
                   output_file = "ASU-2020-Salary-Report.HTML",
                   params = list( url = url.2020 ) )
```

Are you running this rmarkdown::render() command from an R console with utils.R and salary-report.rmd saved in your current working directory?

**Comment by jasminacosta** [comment]
@lecy I used getwd() to see what the directory is for each file and these are the results.

For utilis.R the directory is:

```{r}

> getwd()
[1] "/Users/jasminacosta/montyhall"

```

For salary-report.rmd it is:

```{r}

> getwd()
[1] "/Users/jasminacosta/Downloads"

```

Then for batch.R it is:

```{r}

> getwd()
[1] "/Users/jasminacosta/montyhall"

```

However, I saw that all my files were in my downloads folder.

I am really confused.

**Comment by lecy** [comment]
If all of your files are in the downloads folder, you should be able to knit the report as follows: 

```r
setwd( "/Users/jasminacosta/Downloads" )

## 2020 REPORT
url.2020 <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
rmarkdown::render( input='salary-report.rmd', 
                   output_file = "ASU-2020-Salary-Report.HTML",
                   params = list( url = url.2020 ) )
```

**Comment by jasminacosta** [comment]
@lecy It seemed to work for the batch.R and utilis.R, but I still having issues with the salary-report.rmd. 

<img width="671" alt="Screenshot 2024-02-12 at 5 19 07 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/693d96fa-96f0-4f9b-8d7d-6ed190aba256">

<img width="304" alt="Screenshot 2024-02-12 at 5 19 40 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/4ccc4183-3cc4-4da3-9332-bd4218faf493">

**Comment by lecy** [comment]
You can't always knit a template RMD directly in RStudio. You would knit using the command in batch.R: 

```r
setwd( "/Users/jasminacosta/Downloads" )

## 2020 REPORT
url.2020 <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
rmarkdown::render( input='salary-report.rmd', 
                   output_file = "ASU-2020-Salary-Report.HTML",
                   params = list( url = url.2020 ) )
```

When you run this do you create an HTML file called "ASU-2020-Salary-Report.HTML"?

**Comment by jasminacosta** [comment]
@lecy Yes, I believe so.

<img width="671" alt="Screenshot 2024-02-13 at 3 24 24 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/29ce0e8e-cc7a-4d14-97ae-5d4aeb6c6dfb">

<img width="666" alt="Screenshot 2024-02-13 at 3 24 54 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/9fb76991-c839-4ea9-8470-64e0daf83858">

**Comment by lecy** [comment]
Check your file list to confirm: 

```r
dir()
```
Or else open your downloads folder and look for the file. 

You can also open files from R with shell(): 

```r
# assuming you are in the right wd
shell( "ASU-2020-Salary-Report.HTML" )
```

**Comment by jasminacosta** [comment]
@lecy This is the output I am getting and I am not sure why I am do getting the directory dir()

<img width="666" alt="Screenshot 2024-02-13 at 4 18 34 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/6f719621-9ded-47e9-99c0-f89ebac37ca3">

**Comment by jasminacosta** [comment]
@lecy Understood. 

I installed gender data and tried to run the code in the R console.

```{r}

 setwd( "/Users/jasminacosta/Downloads" )
## 2020 REPORT
url.2020 <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
rmarkdown::render( input='salary-report.rmd',
                    output_file = "ASU-2020-Salary-Report.HTML",
                    params = list( url = url.2020 ) )

```

And I am getting this error:

```{r}

processing file: salary-report.rmd
  |..................................................        |  86% [unnamed-chunk-2]
Quitting from lines 80-100 [unnamed-chunk-2] (salary-report.rmd)
Error in `group_by()`:
! Must group by variables found in `.data`.
Column `title` is not found.
Column `gender` is not found.
Backtrace:
 1. ... %>% mutate(p = round(n / sum(n), 2))
 6. dplyr:::group_by.data.frame(., title, gender)

```

**Comment by lecy** [comment]
Try closing R Studio and executing from a base R console, please.

**Comment by jasminacosta** [comment]
@lecy I closed R studio and executed the code from the R console and I am still getting the same error.

**Comment by lecy** [comment]
Can you please try the following and tell me what you get: 

```r
library( dplyr )
library( pander )
library( knitr )
library( gender )
source( "utils.R" )

URL <- "https://raw.githubusercontent.com/Watts-College/paf-514-template/main/labs/batch-demo/asu-salaries-2020.csv"
d <- read.csv( URL )
d$first.name <- get_first_name( d$Full.Name )
d <- add_gender( d )
d <- add_titles( d )
d <- fix_salary( d )

d <-      
  d %>% 
  filter( title != "" & ! is.na(title) ) %>% 
  filter( Department.Description %in% academic.units )
head(d) %>% pander::pander()
```

**Comment by jasminacosta** [comment]
@lecy I got the following:

```{r}

----------------------------------------------------------------
 first.name   Calendar.Year      Full.Name      Job.Description 
------------ --------------- ----------------- -----------------
   Aaron          2020         Baker, Aaron        Professor    

   Aaron          2020        Fellmeth, Aaron      Professor    

   Aaron          2020         Redman, Aaron      Instructor    

   Aaron          2020        Crippen, Aaron      Instructor    

   Aaron          2020          Bae, Aaron         Lecturer     

   Aaron          2020         Romans, Aaron      Instructor    
----------------------------------------------------------------

Table: Table continues below

 
------------------------------------------------------------------------------
    Department.Description        Salary      FTE   gender        title       
------------------------------ ------------- ----- -------- ------------------
           English              $107,160.00   100    male     Full Professor  

        College Of Law          $164,755.00   100    male     Full Professor  

  SOS Faculty & Researchers     $50,000.00    100    male    Teaching Faculty 

           English              $52,600.00    100    male    Teaching Faculty 

  School of Social Transform    $52,750.00    100    male    Teaching Faculty 

 Social & Behavioral Sciences   $47,979.00    80     male    Teaching Faculty 
------------------------------------------------------------------------------

Table: Table continues below

 
--------
 salary 
--------
 107160 

 164755 

 50000  

 52600  

 52750  

 59974  
--------

```

**Comment by lecy** [comment]
Ok now add: 

```r
t.salary <- 
  d %>% 
  group_by( title, gender ) %>% 
  summarize( q25=quantile(salary,0.25),
             q50=quantile(salary,0.50),
             q75=quantile(salary,0.75),
             n=n() ) %>% 
  ungroup() %>% 
  mutate( p= round( n/sum(n), 2) )

t.salary %>% build_graph( unit="ALL ASU")
```

**Comment by jasminacosta** [comment]
@lecy I ran that also into the R console and received these results:

```{r}

> t.salary <- 
+     d %>% 
+     group_by( title, gender ) %>% 
+     summarize( q25=quantile(salary,0.25),
+                q50=quantile(salary,0.50),
+                q75=quantile(salary,0.75),
+                n=n() ) %>% 
+     ungroup() %>% 
+     mutate( p= round( n/sum(n), 2) )
`summarise()` has grouped output by 'title'. You can override using the `.groups`
argument.
> 
> t.salary %>% build_graph( unit="ALL ASU")
NULL


```

Along with a graph of salaries. 

<img width="560" alt="Screenshot 2024-02-13 at 6 39 28 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/4d4a0c00-83bd-44ad-bcda-75df6d655272">

**Comment by lecy** [comment]
Last thing to test, then: 

```r
URL <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
d <- read.csv( URL )
```

If that works then I'm guessing if you shut down R and open it again then try once more with a fresh console it will work. It could have been a ghost in the machine from other files you had open. 

Otherwise I am stumped because it works on my computer and all of the steps above work fine. If you still get an error please email me your RMD and util.R files.

**Comment by jasminacosta** [comment]
@lecy I ran that as well in the R console and it worked fine. 

I shut down R and ran the code to see if the salary-report.rmd would run properly, but I am still getting the same error. 

Let me send over my files.

**Comment by lecy** [comment]
Check your email - you added extra code to the salary-template.rmd file that was overwriting the prior data steps. If you use the original version it should work fine.

**Comment by jasminacosta** [comment]
@lecy Oh, I see! 

I removed those lines and when I ran the code:

```{r}

setwd( "/Users/jasminacosta/Downloads" )
## 2020 REPORT
url.2020 <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
rmarkdown::render( input='salary-report.rmd',
                   output_file = "ASU-2020-Salary-Report.HTML",
                   params = list( url = url.2020 ) )

```

I got the output

```{r}

processing file: salary-report.rmd
                                                                                                                  
output file: salary-report.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS salary-report.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output ASU-2020-Salary-Report.HTML --lua-filter /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --embed-resources --standalone --variable bs3=TRUE --section-divs --table-of-contents --toc-depth 3 --template /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rmarkdown/rmd/h/default.html --highlight-style zenburn --variable theme=readable --mathjax --variable 'mathjax-url=https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --include-in-header /var/folders/tw/fh99fdy16cg1d8ppmstjmp5w0000gn/T//RtmpI0n6uY/rmarkdown-str121c72b99f561.html 

Output created: ASU-2020-Salary-Report.HTML

```

Then I went to knit the salary-report.rmd and I got the error:

Not sure if that is what is supposed to happen. 

```{r}

processing file: salary-report.rmd

Quitting from lines 30-66 [unnamed-chunk-1] (salary-report.rmd)
                                                                                                            
Error in `file()`:
! cannot open the connection
Backtrace:
 1. utils::read.csv(URL)
 2. utils::read.table(...)
 3. base::file(file, "rt")
Execution halted

```

**Comment by lecy** [comment]
This is how you knit your report template: 

```r
rmarkdown::render( input='salary-report.rmd', ... )
```

When you are creating batches of dozens or hundreds of reports you would not want a separate RMD file for each report that you have to open in R Studio and knit manually.

**Comment by jasminacosta** [comment]
@lecy Yay! 

Got it, that makes sense. 

In that case would I be able to begin the project, or do I need to run that code and it needs to run properly?

```{r}

rmarkdown::render( input='salary-report.rmd' )

```

Because when I ran that code to see what would happen I got the error:

```{r}

processing file: salary-report.rmd
  |.................................                         |  57% [unnamed-chunk-1]
Quitting from lines 30-66 [unnamed-chunk-1] (salary-report.rmd)
Error in `file()`:
! cannot open the connection
Backtrace:
 1. utils::read.csv(URL)
 2. utils::read.table(...)
 3. base::file(file, "rt")

```

Just want to make I am setting up my files correctly before I start adding code to it!

**Comment by lecy** [comment]
The dots were for the omitted parts: 

```r
## 2020 REPORT
url.2020 <- "https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv"
rmarkdown::render( input='salary-report.rmd',
                   output_file = "ASU-2020-Salary-Report.HTML",
                   params = list( url = url.2020 ) )
```

**Comment by jasminacosta** [comment]
@lecy Understood.

Thank you for all your help!
