### ISSUE TITLE
Data Wrangling Exercise Assignment?

### ISSUE THREAD

**Issue by nickmcmullen** [Watts-College/paf-514-template#53]
Hi Professor @lecy,

Is the [data wrangling exercise](https://watts-college.github.io/paf-514-template/schedule/#data-wrangling-exercise) assignment a required component for this course? I see it listed on the Github site and syllabus as 10% of our final grade, but the link to the instructions is empty and I don't see a place to submit anything on Canvas. Wondering if I'm missing something?

Thanks!

**Comment by lecy** [comment]
Nick - I sent an announcement earlier on Canvas. I trust that answered your question.

**Comment by nickmcmullen** [comment]
Yes, thank you!
