### ISSUE TITLE
Final Project: Part 2

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-514-template#57]
Hi @lecy!

I am having another issue on Part 2 of the project when I put all the departments in a loop.

I tried taking t.salary out of the function loop to see if that helps, and I get the same error. 

```{r, fig.height=7, fig.width=10, results="asis"}


for( i in academic.units )
{
  
  d2 <- filter( d, Department.Description == i )
  if( nrow(d2) == 0 ) { next }  
  
  create_salary_table(d2) %>% # create the salary summary by rank & gender table 
  top_five_salaries(d2) %>% # create the top 5 salaries table 
  build_graph( t.salary, unit = i )# build the graph 

  # print the tables:  
  cat( paste('<h3>',"TOP FIVE SALARIES",'</h3>' ) )
  cat( t.rank %>% knitr::kable(format="html") )   

  cat( '<br><hr><br>' )
  
}


```

```{r}

Error in build_graph(., t.salary, unit = i) : unused argument (t.salary)

```

**Comment by lecy** [comment]
This is a good example of workflow. What are the inputs and outputs to each function here? 

```r
  create_salary_table()  # input = ??? >> fx() >> output = salary table for a department
  top_five_salaries()    # input = salary table >> fx() >> output = smaller table of five highest paid in department 
  build_graph( )         # input = salary table >> fx() >> output = graph
```

Note that salary table is the input to both top_five_salaries() and build_graph(). Is that reflected in your piped data recipe here? 

```r
d2 %>%
  create_salary_table() %>%  
  top_five_salaries() %>%  
  build_graph( unit = i )
```

**Comment by jasminacosta** [comment]
> The hint here is the period in the error:
> 
> ```
> Error in build_graph(., t.salary, unit = i) : unused argument (t.salary)
> ```
> 
> The period appears when data is piped to a function. It is the placeholder for the object that is passed to the function through piping. So in your case, whatever is returned from top_five_salaries() here:
> 
> ```r
>   top_five_salaries( d2 ) %>% 
>   build_graph( t.salary, unit = i )
> ```
> 
> So you are sending two tables to the function instead of one. You could use either of these instead:
> 
> ```r
>   top.five <- top_five_salaries( d2 ) 
>   build_graph( top.five, unit = i )
> 
>   top_five_salaries( d2 ) %>% 
>   build_graph( unit = i )
> ```
> 
> Although I am not sure that the top.five salaries table works with the graph. I think that should be the full table of salaries from the department.

@lecy That makes a lot of sense! 

However, I am a little bit confused on which function we should be using if the top.five salaries table does not work with the graph. 

```{r}

for( i in academic.units )
{
  
  d2 <- filter( d, Department.Description == i )
  if( nrow(d2) == 0 ) { next }  
  
  create_salary_table(d2)  # create the salary summary by rank & gender table 
  top.five <- top_five_salaries( d2 ) 
  build_graph( top.five, unit = i )

  # print the tables:  
  cat( paste('<h3>',"TOP FIVE SALARIES",'</h3>' ) )
  cat( t.rank %>% knitr::kable(format="html") )   

  cat( '<br><hr><br>' )
  
}

```



```{r}

Error in plot.window(xlim = c(40000 - 10000, xmax), ylim = c(0, ymax +  : 
  need finite 'xlim' values

```

**Comment by jasminacosta** [comment]
> This is a good example of workflow. What are the inputs and outputs to each function here?
> 
> ```r
>   create_salary_table()  # input = ??? >> fx() >> output = salary table for a department
>   top_five_salaries()    # input = salary table >> fx() >> output = smaller table of five highest paid in department 
>   build_graph( )         # input = salary table >> fx() >> output = graph
> ```
> 
> Note that salary table is the input to both top_five_salaries() and build_graph(). Is that reflected in your piped data recipe here?
> 
> ```r
> d2 %>%
>   create_salary_table() %>%  
>   top_five_salaries() %>%  
>   build_graph( unit = i )
> ```

@lecy I think I fixed the issue based on the inputs and outputs. 

```{r}

for( i in academic.units )
{
  
  d2 <- filter( d, Department.Description == i )
  if( nrow(d2) == 0 ) { next }  
  
  salary.table <- create_salary_table(d2)  
  top.five <- top_five_salaries( d2 ) 
  build_graph( salary.table, unit = i )

  # print the tables:  
  cat( paste('<h3>',"TOP FIVE SALARIES",'</h3>' ) )
  cat( top.five %>% knitr::kable(format="html") )   

  cat( '<br><hr><br>' )
  
}

```

After I adjusted the code a bit I ended up with 42 different graphs. 

<img width="512" alt="Screenshot 2024-02-20 at 8 53 58 PM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/60b80039-8e4b-4afc-a29a-dbf6a2af7235">

**Comment by lecy** [comment]
That looks better!

**Comment by jasminacosta** [comment]
@lecy Thank you for your help!
