### ISSUE TITLE
Part 3 Step 3 Creating a Batch

### ISSUE THREAD

**Issue by Leah-Coffin** [Watts-College/paf-514-template#60]
@lecy 

When I run a batch for 2020 data, I get the error below.  There were no errors in the functions-demo when I created and tested the add_gender.

```
processing file: salary-report.rmd
  |.......................................................................                                    |  67% [data]           
Quitting from lines 45-65 [data] (salary-report.rmd)
Error in `fix.by()`:
! 'by' must specify a uniquely valid column
Backtrace:
 1. global add_gender(d)
 2. base::merge.data.frame(...)
      at utils.R:21:2
 3. base (local) fix.by(by.x, x)
```

This is the line from utils.R:

```
  merged_data <- merge.data.frame(d, gender_table, by.x = "first.name", by.y = "name", all.x = TRUE)
```

It works fine in my functions-demo.rmd.

**Comment by lecy** [comment]
What does your code look like for that step in your functions-demo.rmd vs salary-report? 

Has the first name been added back to the data frame successfully before trying to merge? 

To debug the salary report you can always load the data there directly and walk through the document one chunk at a time to find the problem: 

```r
# FOR MANUAL TESTING ONLY
# URL <- "https://raw.githubusercontent.com/Watts-College/paf-514-template/main/labs/batch-demo/asu-salaries-2020.csv"
# d <- read.csv( URL )
```

**Comment by Leah-Coffin** [comment]
This is part 1, step 3 in my functions demo where I added gender and added it to the data frame (and I am able to see gender and first.name in the data frame)

---
#part 1 step 3

add_gender <- function(d) {

  # Build gender table for the names
  gender_table <- gender(unique.first.names)
  
  # Merge gender information with the original data
  merged_data <- merge.data.frame(d, gender_table, by.x = "first.name", by.y = "name", all.x = TRUE)
  
  # Assign "uncoded" to names with missing genders
  merged_data$gender[ is.na(merged_data$gender) ] <- "uncoded"
  merged_data$gender <- factor( merged_data$gender, levels=c("male","female","uncoded") )
  
  return(merged_data)
}
d <- add_gender(d)
---

**Comment by Leah-Coffin** [comment]
When I run manual testing in the salary-report, I get the following error:  Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column

**Comment by lecy** [comment]
(1) I'm assuming you checked that **d** has class() data.frame and includes the column "first.name" before passing it to the function? Sometimes the objects get mangled in prior steps - you did not provide a reproducible example so I can't inspect your workflow. Those are easy things to eliminate from the list. 

(2) Recall that function are input-output machines. What is the information the function needs? You are currently passing it only **d**, but I see that you then reference `unique.first.names`, which has not been defined elsewhere inside the function. You should be passing that explicitly if you are not creating it inside the function:

```r
# create inside the function from d
unique.first.names <- unique( d$first.name )

# pass to the function
add_gender <- function( d, unique.first.names )
``` 

The base R function name is **merge()**, not **merge.data.frame()**. I am not sure where you found that function? I suspect that is your issue, though. 

https://stat.ethz.ch/R-manual/R-patched/library/base/html/merge.html

**Comment by lecy** [comment]
Side note - GitHub speaks markdown, so you format code here the same way you do in R Markdown documents - with "fences": 

````
```
# some code
x <- 1:10
y <- 2*x + rnorm(100)
plot( x, y )
```
````

```
# some code
x <- 1:10
y <- 2*x + rnorm(100)
plot( x, y )
```

If you reference the language directly it will add syntax highlighting specific to the language: 

````
```r
# some code
x <- 1:10
y <- 2*x + rnorm(100)
plot( x, y )
```
````

```r
# some code
x <- 1:10
y <- 2*x + rnorm(100)
plot( x, y )
```

The only difference is that R Markdown adds the squiggly brackets so you can add chunk arguments: 

````
```{r}
````

````
```{r, results="asis"}
````
