### ISSUE TITLE
Lab 2 Code Error 

### ISSUE THREAD

**Issue by lindaalvarez** [Watts-College/paf-514-template#67]
@castower 

Hello, I am running into a code error when trying to create the game play function. At first I thought it was a problem with my personal code so I recreated Lab 1 with the posted solutions and yet the same error shows up. Attached is a screenshot of my code so you are able to see. Thank you for your help!

<img width="1440" alt="Screen Shot 2024-09-02 at 9 24 20 PM" src="https://github.com/user-attachments/assets/0251e0c3-8b17-4ade-8356-6fc15902d0a6">

**Comment by castower** [comment]
Hello @lindaalvarez ,

It appears somewhere in your code you're calling the function a.pick(), but it isn't defined.
