### ISSUE TITLE
Lab 02 - Part II

### ISSUE THREAD

**Issue by shumway99** [Watts-College/paf-514-template#72]
Hello @castower and anyone else who can help! :) 

Working on Lab 02, and on Part II I keep running into issues, almost like the play_game function doesn't know which functions it's pulling from? I don't know how to explain it. Here are some examples:

This is where I start, with code like the first play_game function and that of Part I (I'm probably just incorporating the number of goats and cars incorrectly and that might be my whole problem haha): 
![image](https://github.com/user-attachments/assets/d31f7a72-0b10-405d-9eaf-ffabfb6d2a9b)
And it gives me this "argument 'num.goats' is missing with no default" error, so then I try putting the number of goats and cars into the new.game function like so:
![image](https://github.com/user-attachments/assets/a4379d97-4909-46b9-8b37-7de3798f65be)
But then it says the argument "game" is missing with no default, so then I try putting new.game into the first.pick function to see if that helps like so:
![image](https://github.com/user-attachments/assets/f8d1a3f9-c9ad-44c8-88d4-8366ca71ff1f)
and then I get the error that argument "a.pick" is missing, with no default. 
It just keeps going like that no matter what I try to mess with or add in or take out from the play_game wrap function, and I'm not sure what's going wrong. I don't even know what I don't know haha!

I don't know if this post made any sense, but any help would be much appreciated! 

Thank you!!

**Comment by castower** [comment]
Hello @shumway99 ,

You'll want to make sure that you have inputs for each of the inputs you defined when creating your functions.

How many defined inputs do you have for change_door_challenge_2()? It appears there are at least 4 and you only have 3 defined here.

**Comment by shumway99** [comment]
That was my problem! Thank you so much!
