### ISSUE TITLE
Lab 3 Q2c

### ISSUE THREAD

**Issue by pmorrizonaz** [Watts-College/paf-514-template#76]
Hi @castower ,

I'm running into an issue on the last question for lab 3, trying to get the last word for each title and then determining the most common last word. I was able to find the most common first word in 2b with no problem, so I used mostly the same code from that for 2c. However, the `strsplit()` for 2c doesn't seem to be working fully - for some reason, many outputs have the last two words of each title instead of just the last word. My code is below:

titles.no.punction <- gsub("\\?|\\.|!", "", d$title)

get_last_word <- function(x)
{
  word.list <- strsplit(x, split = " ")
  word.vector <- unlist(word.list)
  last.word <- tail(word.vector, n=1)
  print(last.word)
}

last.word.list <- sapply(titles.no.punction, get_last_word)
last.word.list <- tolower(last.word.list)
last.word.count <- table(last.word.list)
last.word.count <- sort(last.word.count, decreasing = TRUE)
head(last.word.count, n=5)

As an example, when I do `get_last_word(titles.no.punctuation[1])`, the output is `[1] "Word2Vec Model"`. I would greatly appreciate any help or advice!

**Comment by castower** [comment]
Hello @pmorrizonaz,

It's likely that there are some non-breaking/ "hair" spaces remaining in the strings. These appear in the code as unicode a0. 

See the steps below to identify and remove them: 

```
# Store strings
strings <- strsplit(d$title, " ")
head(strings)

# View string with space
test <- strings[1][[length(strings[1])]][9]
test

# See non-breaking space/"hair space" are still there
charToRaw(test)

# Replace (\u is for unicode)
gsub("\uA0", " ", test)

# Test split
test <- gsub("\uA0", " ", test)
strsplit(test, " ")

# Replace non-breaking/"hair" space, see new split
d$title2 <- gsub("\uA0", " ", d$title)
strings <- strsplit(d$title2, " ")
head(strings) 
```

Let me know if you have another questions!
