### ISSUE TITLE
Lab 03 - Cleaning Titles

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/paf-514-template#77]
I noticed that some of my titles have quotation marks, such as the following: 

![image](https://github.com/user-attachments/assets/b01e0662-e874-48fe-a697-57d98533e9ff)

Should I be cleaning those titles to remove the quotation marks?

**Comment by castower** [comment]
Hello @CTNovoa,

Having the quotation marks will alter whether those words are pulled when you select the first & last words so replacing them will assist with cleanup.

**Comment by CTNovoa** [comment]
Done. Good point, thank you!
