### ISSUE TITLE
Lab 03 - Q3: Length of Title

### ISSUE THREAD

**Issue by tnt2501** [Watts-College/paf-514-template#79]
Hi @castower,

I am having some difficulty with question 3 on lab 3. I have the following code below which I know is not correct. My thought process was thinking that I might need to put clap.length.score inside of a loop. Then replacing the 5 inside the filter with the current index of the loop (I was using the 5 value to test). Is this idea on track? Can you give me any guidance to move forward with the problem? Thank you!

```{r}
d$title <- tolower(d$title)
word.list <- strsplit(d$title, " ")


word.count <- sapply(word.list, length)
d$word_count <- word.count


clap.score.length <- log( d$claps+1 )

clap.length.score <- d %>%
  select(title, claps, clap.score) %>%
  filter(length(title) == 5)
```

**Comment by castower** [comment]
Hello @tnt2501,

You can approach this problem by focusing on the data set as a whole. Once you have counted the number of words and added it to your data set and you have clap.score in your data set, then you have all of your pairs together. Next, you can do your regression and create a box plot to compare this relationship.

You may find it helpful to review the section on the box plot formula here:
https://www.datamentor.io/r-programming/box-plot#:~:text=Boxplot%20form%20Formula

This same method can be applied using plot() where you treat the number of words in the title as your factor (your categorical variable) and clap.score as your numeric variable.

Let me know if you have any other questions!
