### ISSUE TITLE
Loop error - object 'd' not found 

### ISSUE THREAD

**Issue by Rachel-Judd** [Watts-College/paf-514-template#8]
Update: I think I figured this out. If I add print(results) it displays the data frames. 

----------------------------------
When I try to run the code in the example in the lecture notes under "Loops", it is returning an error. 

Error in get_slope(d) : object 'd' not found

Is this because d is not defined? Wondering if it could be because I don't have all the packages needed to run the loop. 

```r
get_slope <- function( d, N=10 )
{             
  d.sample <- dplyr::sample_n( d, size=N )
  m <- lm( y ~ x, data=d.sample )
  b1 <- (coef( m ))[2]
  ci <- confint( m )
  ci.b1.lower <- ci[2,1]
  ci.b1.upper <- ci[2,2]
  df <- data.frame( b1, ci.b1.lower, ci.b1.upper )
}

results <- NULL                 
for( i in 1:100 )
{
   one.model <- get_slope( d )
   results <- dplyr::bind_rows( results, one.model )
}
```

**Comment by lecy** [comment]
There should be a link to the script where these functions are defined right below the example: 

https://watts-college.github.io/paf-514-template/lectures/week-02/

https://raw.githubusercontent.com/DS4PS/cpp-527-fall-2020/master/lectures/loop-example.R

In that script you will find **d**: 

```r
## GENERATE DATA
## regression slope = 2

x <- 1:100
y <- 2*x + rnorm(100,0,75)
d <- data.frame( x, y )

plot( x, y, pch=19, main="Population Data" )
summary( lm( y ~ x ) )
```

In some cases I try to get you to focus on reading the code, not running it right away. 

I can add it to the example, though, so it is a little more explicit.

**Comment by lecy** [comment]
I added a link to the full regression simulation code if you want to dive into it more: 

https://github.com/lecy/regression-simulations

But the example was mainly be used to show a case where you might use a loop - the specifics of that code are not important for this lecture.
