### ISSUE TITLE
Lab 4: Tabulate top word counts

### ISSUE THREAD

**Issue by kdelaro2** [Watts-College/paf-514-template#81]
Hello @castower I'm running into an issue with Part 2 of the lab specifically when I attempt to tabulate top word counts. 

When I enter the following code: 

`tokens %>% dfm( stem=F) %>% topfeatures( )`

I receive the following error: 
! The `stem` argument of `dfm()` was deprecated in quanteda 3.0
  and is now defunct.
ℹ Please use `dfm_stem()` instead.
Backtrace:
 1. tokens %>% dfm(stem = T) %>% topfeatures()
 3. quanteda::dfm(., stem = T)
 4. quanteda:::check_defunct_dfm_args(names(as.list(sys.call())[-1]))
 5. lifecycle::deprecate_stop(...)
 6. lifecycle:::deprecate_stop0(msg)

I tried using `dfm_stem()` as suggested, but I received another error saying the function was not found. I also checked to see if I had the newest version of R studio and I am using R version 4.4.1 (2024-06-14). 

Any insight on how to resolve this would be greatly appreciated, thank you!

**Comment by castower** [comment]
Hello @kdelaro2 
You can see the solution here: https://github.com/Watts-College/paf-514-template/issues/80#issuecomment-2357041827

Let me know if you have any questions!

**Comment by kdelaro2** [comment]
Thank you for your help!
