### ISSUE TITLE
Lab 4: Trimws()

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/paf-514-template#82]
Hi there, @castower ! I am likely overthinking this a bit, but I wanted to clarify:

- Do we only want to remove the white spaces at the **end** of each mission statement?
- Do we also want to remove the blank mission statements from our dataset? 

Further, for some reason I either can't get my trimws() function to work properly, or the grep() function I am using to pull the missions with trailing spaces at the end is not working properly (I am using this to double check my work, that the white space was indeed trimmed). I would love your thoughts. 

I tried this to grab trailing spaces at the end:
grep( pattern="^\\S|\n\\s$", x=dat$mission, value=TRUE ) 

And tried this for trimws()

dat$mission.v2 <- trimws(dat$mission)

I recognize I could have just updated the original mission variable, I just was worried about doing it wrong and messing up the dataset.

Thank you for the assistance! I know this should be simple...not sure why it is tripping me up.

**Comment by castower** [comment]
Hello @CTNovoa ,

1. Yes, you want to find the count of strings with trailing spaces at the end of the strings (if they exist) and then trim them. Keep in mind, if they do exist, they'll appear as an extra space at the end of a string with other characters such as "string with trailing space. "

2. You just need to count the strings with blanks (which will appear as empty strings '') and spaces (which have only whitespace ' '). You don't have to remove them, but you can if you want.

**Comment by castower** [comment]
@CTNovoa I missed the third part of your question!

You just want to see if there are strings with space at the end, so you can use \\s or the special space category [[:space:]] to find if they're in the string at the end ($).

**Comment by CTNovoa** [comment]
Great! I am not sure how that got more complicated in my head. Thanks for clarifying and for the guidance.
