### ISSUE TITLE
Lab 04 - Part III

### ISSUE THREAD

**Issue by tnt2501** [Watts-College/paf-514-template#83]
Hi @castower, For Part III we have to test the error rate for how many organizations in my sample do NOT belong there. How would we do this? Is the goal to manual read the 20 randomly selected mission statements and personally decide? Do I exclude a word that what identifies some false positive via the following example code? (Am I on the right track here?) 

```{r} 
criteria.01 <- grepl( "black community", dat$mission ) 
criteria.02 <- grepl( "african american", dat$mission ) 
criteria.03 <- grepl( "civil rights", dat$mission ) 
criteria.04 <- grepl( "people of color", dat$mission ) 
criteria.05 <- ! grepl( "black bear", dat$mission )  # exclude false positives 
criteria.06 <- ! grepl( "blacksmith", dat$mission )
```

```{r}
these.nonprofits.targetmissions <- ( criteria.01 | criteria.02 | criteria.03 | criteria.04 ) &  (criteria.05 | criteria.06)
                                                                                                  
sum( these.nonprofits.targetmissions )

```

Thank you in advance!

**Comment by castower** [comment]
@tnt2501 
Yes, you can create the grouping that you believe does the best job of capturing your expected outcome and then manually count how many are false positives in your sample from your final criteria.
