### ISSUE TITLE
Lab 5 Site Deployment

### ISSUE THREAD

**Issue by ClaudiaHebert** [Watts-College/paf-514-template#84]
Hi @castower,

I am having some trouble having my website actually deploy. Initially it did but as I've continued following along the lab steps, I must have messed something up. 

My url: claudiahebert.github.io/lab5.buildingwebsite now says "no site found." The deployment keeps failing with this error:  "Logging at level: debug github-pages 232 | Error: (/github/workspace/./_config.yml): did not find expected key while parsing a block mapping at line 9 column 1"

This is what lines 8-12 look like: 
# Name of website
title: Github Website Learning

# Your name to show in the footer
author: Claudia Hebert

I tried adding quotation marks around the website title and that didn't fix it. I also ran the larger section through a YAML checker which indicated everything was fine. How do I fix this?

**Comment by ClaudiaHebert** [comment]
Thanks for the quick response! I updated the repo name and changed the table of contents back to include the name and url variables. (Although the original Beautiful Jekyll  code does not have these, that was an addition I made to try and fix). 

However I am continuing to have the same issue with the same error message. Any thoughts?

**Comment by castower** [comment]
Hi @ClaudiaHebert,

I missed your follow-up question.

Looking at the Jekyll error message: https://github.com/ClaudiaHebert/lab5_website/actions/runs/11001446420/job/30546150286, your error is on line 9. Try entering the website name without the underscores. 

I also see your note about the table of contents, you'll want to leave the format the same as the template: https://github.com/DS4PS/beautiful-jekyll/blob/master/_config.yml

**Comment by ClaudiaHebert** [comment]
@castower I updated both of these things but am receiving the same error unfortunately

**Comment by castower** [comment]
@ClaudiaHebert You can try removing your customized file and putting the default one back in the repo. It looks like there's a formatting error somewhere in the file.

**Comment by castower** [comment]
@ClaudiaHebert final note, on line 109, the '#' symbol should be spaced from the hex code and on line 113 one of the comments is missing the '#' symbol.

**Comment by ClaudiaHebert** [comment]
@castower I just realized the same and this fixed it! I had a couple syntax errors in the colors but I hadn't even checked there because I figured it had to be close to line 9 if not actually line 9. Now I know not to trust the line number it gives me haha. Thank you!
