### ISSUE TITLE
LAB 5 - Step 04 - Formatting using <div> is not showing up

### ISSUE THREAD

**Issue by anaitab** [Watts-College/paf-514-template#85]
I added the <div .... with the corresponding formatting parameters around steps ### 1;  ### 2; and  ### 3; but the appearance of these sections does not change. Do you have any suggestions about why and how to fix it?
Example: 

```
<div class="gs-section-01" markdown="1" style="background-color: #333333; color: #006400; font-size: 25 px ; font-family: 'Arial', sans-serif ;">
    
### 1. Fork the Beautiful Jekyll repository 

Fork the [repository](https://github.com/daattali/beautiful-jekyll) 
by clicking the Fork button on the top right corner in GitHub.

</div>
```

**Comment by castower** [comment]
Hello @anaitab ,

If you take a look at the Code-Through video, a solution for this is provided around the 1 hour and 20 minute mark.

Let me know if you have any issues following those steps!
