### ISSUE TITLE
Lab 5- Alternative to Atom?

### ISSUE THREAD

**Issue by anaitab** [Watts-College/paf-514-template#86]
The tutorial 'Internetting is hard' recommends the text editor 'Atom'. It has been discontinued since the tutorial was published. Is there a recommended replacement for it? Has Atom been replaced by the editing environment on GitHub?

**Comment by castower** [comment]
@anaitab 

For the purposes of our lab, you can just edit directly in GitHub or if you've connected the repo in GitHub desktop, you can use the RStudio editor.

If you want a more robust editor in the future, I've found VSCode to be a great alternative to Atom: https://code.visualstudio.com/
