### ISSUE TITLE
Lab06 Part 1

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/paf-514-template#87]
When knitting my file, everything looks correct except for the "twitter" component. Which is a bit odd, because my Github component is working well and it is worded the same way in my code. 

In the knitted document, I can see that it is creating a code that appears to be correct (i.e., it begins and ends appropriately with Amrish's twitter URL in between that content). Yet, for some reason the icon with the link is not appearing:

![image](https://github.com/user-attachments/assets/84505e62-67e5-4199-9a83-b7df42a623db)

I have tried to troubleshoot, but can't figure out why this is happening. Particularly since this code is almost identical to my github code and that is working properly. Thanks for the help!

**Comment by castower** [comment]
Hello @CTNovoa,

It's difficult to tell the exact problem without seeing the source code, but it looks like there is either an extra set of tags around the code or the SVG file isn't loading properly. Are you pulling the code from the fontawesome package?

Example for home:
```
cat(paste0( '   <a class="item-link" href="', WEBSITE, '" title="Website">' ), fontawesome::fa( name="home" ), '</a>')
```

**Comment by CTNovoa** [comment]
Hmm, mine looks similar: 

  if (TWITTER != "") {
    cat(paste0('     <a class="item-link" href="',TWITTER,'" title="Twitter">'), fontawesome::fa( name="twitter" ),'</a>')
  cat( '\n' )
  cat( '\n' )
  }

**Comment by castower** [comment]
@CTNovoa yes, that looks correct. If you send me your .RMD file I can take a closer look

**Comment by CTNovoa** [comment]
Sent, thank you @castower !

**Comment by castower** [comment]
Hello @CTNovoa,

Thanks for sending it! You're missing your `cat('</div>')` to close the item-links div. You currently only have the div to close the entire section. 

Let me know if you have any other questions.

**Comment by CTNovoa** [comment]
Thank you so much! Would that look like this, because I am still running into the same error, but I recognize I may be placing it incorrectly. 

![image](https://github.com/user-attachments/assets/5927c9dc-4868-491a-8f03-ec5b2fc8d972)

**Comment by castower** [comment]
@CTNovoa 

You'll want to place the closing div after all the sections for GitHub, Website, and Twitter.

Also make sure you have consistent spacing.

Example:

```
  if (TWITTER != "") {
  cat(paste0( '   <a class="item-link" href="', TWITTER, '" title="Twitter">' ), fontawesome::fa( name="twitter" ), '</a>')
  cat( '\n' )  # line break 
  cat( '\n' )  # line break
}
cat( '  </div>' )
```
