### ISSUE TITLE
Lab06 Part 2 - Knitting Issue

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/paf-514-template#88]
I can't seem to figure why my code is halting (at the end of all of my code) and then not producing a knitted HTML file...

![image](https://github.com/user-attachments/assets/4d67d4ab-3640-428d-8950-ea534c384537)

**Comment by castower** [comment]
@CTNovoa 

A couple possibilities:
- Do you have a 'positions' category in your input file?
- Did you update the glue function to remove the trailing comma?

**Comment by CTNovoa** [comment]
I still have research_positions and industry_positions from the original file.

And yes, I removed the trailing comma. 

I don't have "writings," so I did try to remove that.  I am attempting to make this accurate to my current resume and I don't have any published writings to share :)

**Comment by CTNovoa** [comment]
When I just run the "positions" and "education" sections on their own in my RMD file, they do appear to run properly.

**Comment by castower** [comment]
@CTNovoa Does it also run if you restart the session and clear the environment?

**Comment by CTNovoa** [comment]
Great question, no. After I cleared the environment and restarted, I got the following errors:
 
![image](https://github.com/user-attachments/assets/1a6bc021-7ba8-4fcc-b6f3-e01b233c359b)

**Comment by castower** [comment]
@CTNovoa 

Is this after running all the chunks? Or just those two?

You'll need to run them all to load the libraries and import the functions. Then you can see if you're able to replicate the errors you're getting when knitting.

**Comment by CTNovoa** [comment]
Oops, you're right, I was getting ahead of myself :) apologies. After running all the chunks those two chunks do still run within the RMD file.

**Comment by castower** [comment]
No problem! Email it to me and I'll take a look @CTNovoa

**Comment by castower** [comment]
Hello @CTNovoa,
I was able to run the file and it gave me the following error:

```
 In grepl("^\\s*$", x) : input string 1 is invalid
3: In gsub(paste0("[\n]{2,}(", fence, "|    )"), "\n\n\\1", x) :
  unable to translate '### Management Research Analyst
```

This is related to an encoding issue:
https://github.com/rstudio/shinytest/issues/206 

To fix it, you can use read.csv2 instead of read_csv and set the encoding during import:
`read.csv2(file('positions.csv', encoding="UTF-8"), sep=",", header = TRUE)` 
https://stackoverflow.com/questions/23699271/force-character-vector-encoding-from-unknown-to-utf-8-in-r

**Comment by CTNovoa** [comment]
Thank you! I am so sorry, but I am not sure how to "set the encoding during import." I am changing the options during the import when I import dataset "from text (readr)" but it isn't changing the code in a way that makes it look like yours...
