### ISSUE TITLE
Final Lab Demo Report Samples

### ISSUE THREAD

**Issue by avidsoccer** [Watts-College/paf-514-template#89]
@castower
I am unable to view the report samples.  In both cases, I get the same result.  I have seen authentication errors when opening content all session, but I have found a way around in other cases.  Please point me to the step(s) I missed or an alternative path to the files.  When attempting to view from the assignment page, I see an access denied page "Access to this page is limited to authorized users. You do not currently have permission to view this page."  This has been consistent throughout the session.  From the instructions, I have usually been able to open the files.  In this case, the page returns

{
    "errors": {
        "name": "UnauthorizedError",
        "message": "JWT is required"
    }
}

Robert Neill

**Comment by castower** [comment]
Hello @avidsoccer,

I just emailed you both files via Canvas mail. Are you able to access the source files? If not, I can send those as well.

I'm sorry to hear this has been an issue throughout the session! Have you tried multiple browsers? I know Firefox and Google Chrome typically work well with Canvas. You can also contact the Tech Help Desk (click the question mark symbol on the left hand side in Canvas) and ask them to check your permissions; I double-checked on my test student account and I am able to open all the files so hopefully they can fix your access.

**Comment by avidsoccer** [comment]
@castower 
I have both gender files, salary-report.html, salary-report.rmd, utils.R, and batch.R.  Thank you for the quick response.
