### ISSUE TITLE
Lab-02-Part II

### ISSUE THREAD

**Issue by gmendez9** [Watts-College/paf-514-template#9]
Hi - I am unable to identify the issue that is leading to the following error being returned:

> play_game()
Error in select_door(game = a.game) : unused argument (game = a.game)

Any help here would be highly appreciated. Thank you. Here is my code In its entirety for Part II

```{r}
### build door function - STEP ONE

build_doors <- function( n ){ return( 1:n ) }

# create game function - STEP 2

create_game <- function( num.goats, num.cars )  # <- NEW ARGUMENTS
{
    a.game <- sample( x=rep( c("goat","car"), c(num.goats,num.cars) ), 
                      size=(num.goats+num.cars), replace=F )
    return( a.game )
}

## Step Three - Select Door Function

select_door <- function( )
{
  doors <- build_doors() 
  a.pick <- sample( doors, size=1 )
  return( a.pick )  
}


### Open goat door - STEP THREE

open_goat_door <- function( game, a.pick )
{
   doors <- build_doors()
   # if contestant selected car,
   # randomly select one of two goats 
   if( game[ a.pick ] == "car" )
   { 
     goat.doors <- doors[ game != "car" ] 
     opened.door <- sample( goat.doors, size=1 )
   }
   if( game[ a.pick ] == "goat" )
   { 
     opened.door <- doors[ game != "car" & doors != a.pick ] 
   }
   return( opened.door ) 
}

#### Change door function - STEP FOUR

change_door <- function( stay=T, opened.door, a.pick )
{
   doors <- build_doors()
   
   if( stay )
   {
     final.pick <- a.pick
   }
   if( ! stay )
   {
     final.pick <- doors[ doors != opened.door & doors != a.pick ] 
   }
  
   return( final.pick ) 
}

# Determine winner function insert - STEP FIVE


determine_winner <- function( final.pick, game )
{
   if( game[ final.pick ] == "car" )
   {
      return( "WIN" )
   }
   if( game[ final.pick ] == "goat" )
   {
      return( "LOSE" )
   }
}


# Simulation set up - STEP SEVEN
play_game <- function( num.goats=7, num.cars=3 )
{

  new.game <- create_game( num.goats, num.cars )
  first.pick <- select_door( game=new.game )
  opened.door <- open_goat_door( new.game, first.pick )
  final.pick.stay <- change_door( stay=T, opened.door=opened.door, a.pick=first.pick )
  final.pick.switch <- change_door( stay=F, opened.door=opened.door, a.pick=first.pick )
  outcome.stay <- determine_winner( final.pick.stay, new.game  )
  outcome.switch <- determine_winner( final.pick.switch, new.game )
 
  strategy <- c( "stay","switch" )
  outcome <- c( outcome.stay,outcome.switch )
  game.results <- data.frame( strategy, outcome,
                              stringsAsFactors=F )
  return( game.results )
}

play_game()


# step 8

results.df <- NULL   # collector

for( i in 1:10000 )  # iterator
{
  game.outcome <- play_game(num.goats=7, num.cars=3)
  # binding step
  results.df <- rbind( results.df, game.outcome )
}
table( results.df ) %>% 
  prop.table( margin=1 ) %>% 
  round( 2 ) 


results.df <- NULL   # collector

for( i in 1:10000 )  # iterator
{
  game.outcome <- play_game(num.goats=8, num.cars=2)
  # binding step
  results.df <- rbind( results.df, game.outcome )
}
table( results.df ) %>% 
  prop.table( margin=1 ) %>% 
  round( 2 ) 


# 10 total
results.df <- NULL   # collector

for( i in 1:10000 )  # iterator
{
  game.outcome <- play_game(num.goats=9, num.cars=1)
  # binding step
  results.df <- rbind( results.df, game.outcome )
}
table( results.df )
```

**Comment by gmendez9** [comment]
Changed the open goat door function: now getting this error --> Error in build_doors() : argument "n" is missing, with no default

### Open goat door - STEP THREE

open_goat_door <- function( game, a.pick )
{
   doors <- build_doors( n=length(game) )
   doors.that.can.be.opened <- doors[ ! ( game == "car" | doors == a.pick ) ]
   opened.door <- sample( doors.that.can.be.opened, size=1 )
   return( opened.door ) # number between 1 and N
}

also changed the change door function to match the solution set:

#### Change door function - STEP FOUR

change_door <- function( stay=T, opened.door, a.pick )
{
   doors <- build_doors()
   
   if( stay )
   {
     final.pick <- a.pick
   }
   if( ! stay )
   {
    available.doors <- doors[ doors != opened.door & doors != a.pick ]
     final.pick  <- sample( available.doors, size=1 ) 
   }
  
   return( final.pick )  # number between 1 and 3
}

**Comment by gmendez9** [comment]
I think maybe I need to change the argument to n=10?

**Comment by lecy** [comment]
You define the select_door() function without arguments: 

```r
select_door <- function( )
{
  doors <- build_doors() 
  a.pick <- sample( doors, size=1 )
  return( a.pick )  
}
```
Then you call it with arguments: 
```r
play_game <- function( num.goats=7, num.cars=3 )
{
  new.game <- create_game( num.goats, num.cars )
  first.pick <- select_door( game=new.game )  # <<<
```

You are also need the size argument to build the doors correctly: 

```r
build_doors <- function( n ){ return( 1:n ) }
```

But you are not passing that to select_door(), so there is no way build_doors() would know what that value should be. 

```r
select_door <- function( )
{
  doors <- build_doors() 
  ...
}
```

**Comment by lecy** [comment]
Same problem here: 

```r
change_door <- function( stay=T, opened.door, a.pick )
{
   doors <- build_doors()
   
   if( stay )
   {
     final.pick <- a.pick
   }
   if( ! stay )
   {
    available.doors <- doors[ doors != opened.door & doors != a.pick ]
     final.pick  <- sample( available.doors, size=1 ) 
   }
  
   return( final.pick )  # number between 1 and 3
}
```

In the previous version we always had 2 goats and one car, so we could hard code the game size into **build_doors()** because it was a constant. In a dynamic world the door numbers will change with game size, so that function now needs that information to be explicit (passed as an argument in one way or another - pass the number, or pass the game and check its size, etc.).

**Comment by gmendez9** [comment]
> You define the **select_door()** function without arguments:
> 
> ```r
> select_door <- function( )
> {
>   doors <- build_doors() 
>   a.pick <- sample( doors, size=1 )
>   return( a.pick )  
> }
> ```
> 
> Then you call it with arguments:
> 
> ```r
> play_game <- function( num.goats=7, num.cars=3 )
> {
>   new.game <- create_game( num.goats, num.cars )
>   first.pick <- select_door( game=new.game )  # <<<
> ```
> 
> You are also need the size argument to build the doors correctly:
> 
> ```r
> build_doors <- function( n ){ return( 1:n ) }
> ```
> 
> But you are NEITHER passing the argument to **select_door()**, NOR using it in **build_doors()**, so there is no way **build_doors()** would know what that value should be.
> 
> ```r
> select_door <- function( )
> {
>   doors <- build_doors() 
>   ...
> }
> ```

I fixed these errors, the code produced the following results:

      outcome
strategy LOSE  WIN
  stay   0.70 0.30
  switch 0.65 0.35
        outcome
strategy LOSE  WIN
  stay   0.81 0.19
  switch 0.77 0.23
        outcome
strategy LOSE  WIN
  stay   0.90 0.10
  switch 0.88 0.12

**Comment by gmendez9** [comment]
> Same problem here:
> 
> ```r
> change_door <- function( stay=T, opened.door, a.pick )
> {
>    doors <- build_doors()
>    
>    if( stay )
>    {
>      final.pick <- a.pick
>    }
>    if( ! stay )
>    {
>     available.doors <- doors[ doors != opened.door & doors != a.pick ]
>      final.pick  <- sample( available.doors, size=1 ) 
>    }
>   
>    return( final.pick )  # number between 1 and 3
> }
> ```
> 
> In the previous version we always had 2 goats and 1 car, so we could hard code the game size into **build_doors()** because it was a constant. In a dynamic world the door numbers will change with game size, so that function now needs that information to be explicit (passed as an argument in one way or another - pass the number, or pass the game and check its size, etc.).

Here I am still not exactly sure how to edit the code for the change door function. Am I using the num.cars and num.goats arguments or the number of doors? Sorry for not being clear. Here is my full code after the edits suggested:
### build door function - STEP ONE

build_doors <- function( n=10){ return( 1:n ) }

# create game function - STEP 2

create_game <- function( num.goats, num.cars )  # <- NEW ARGUMENTS
{
    a.game <- sample( x=rep( c("goat","car"), c(num.goats,num.cars) ), 
                      size=(num.goats+num.cars), replace=F )
    return( a.game )
}

## Step Three - Select Door Function

select_door <- function(game )
{
  doors <- build_doors(n=length(game)) 
  a.pick <- sample( doors, size=1 )
  return( a.pick )  # number between 1 and 10
}



### Open goat door - STEP THREE

open_goat_door <- function( game, a.pick )
{
   doors <- build_doors( n=length(game) )
   doors.that.can.be.opened <- doors[ ! ( game == "car" | doors == a.pick ) ]
   opened.door <- sample( doors.that.can.be.opened, size=1 )
   return( opened.door ) # number between 1 and N
}
#### Change door function - STEP FOUR

change_door <- function( stay=T, opened.door, a.pick )
{
   doors <- build_doors( )
   
   if( stay )
   {
     final.pick <- a.pick
   }
   if( ! stay )
   {
    available.doors <- doors[ doors != opened.door & doors != a.pick ]
     final.pick  <- sample( available.doors, size=1 ) 
   }
  
   return( final.pick )  # number between 1 and 3
}

# Determine winner function insert - STEP FIVE


determine_winner <- function( final.pick, game )
{
   if( game[ final.pick ] == "car" )
   {
      return( "WIN" )
   }
   if( game[ final.pick ] == "goat" )
   {
      return( "LOSE" )
   }
}


# Simulation set up - STEP SEVEN
play_game <- function( num.goats=7, num.cars=3 )
{

  new.game <- create_game( num.goats, num.cars )
  first.pick <- select_door(game=new.game  )
  opened.door <- open_goat_door( new.game, first.pick )
  final.pick.stay <- change_door( stay=T, opened.door=opened.door, a.pick=first.pick )
  final.pick.switch <- change_door( stay=F, opened.door=opened.door, a.pick=first.pick )
  outcome.stay <- determine_winner( final.pick.stay, new.game  )
  outcome.switch <- determine_winner( final.pick.switch, new.game )
 
  strategy <- c( "stay","switch" )
  outcome <- c( outcome.stay,outcome.switch )
  game.results <- data.frame( strategy, outcome,
                              stringsAsFactors=F )
  return( game.results )
}

play_game( )


# step 8

results.df <- NULL   # collector

for( i in 1:10000 )  # iterator
{
  game.outcome <- play_game(num.goats=7, num.cars=3)
  # binding step
  results.df <- rbind( results.df, game.outcome )
}
table( results.df ) %>% 
  prop.table( margin=1 ) %>% 
  round( 2 ) 


results.df <- NULL   # collector

for( i in 1:10000 )  # iterator
{
  game.outcome <- play_game(num.goats=8, num.cars=2)
  # binding step
  results.df <- rbind( results.df, game.outcome )
}
table( results.df ) %>% 
  prop.table( margin=1 ) %>% 
  round( 2 ) 


# 10 total
results.df <- NULL   # collector

for( i in 1:10000 )  # iterator
{
  game.outcome <- play_game(num.goats=9, num.cars=1)
  # binding step
  results.df <- rbind( results.df, game.outcome )
}
table( results.df )%>% 
  prop.table( margin=1 ) %>% 
  round( 2 )

**Comment by lecy** [comment]
The skill you are practicing here is workflow:

* what information does each function need to work (which arguments are needed to allow the information to be passed to the function)?
* how can we return the results of the function in a way they can be passed to the next step? 

If the game size is variable, one approach is to create a **game.size** variable at the start, then pass that to the functions that need it. Note that when build_doors() is inside another function, you can pass the value though both:

```r
f_1 <- function( a )
{  
   f_2( a )
}
```

The other approach is to generate game size from other objects like game: length(game).

```r
f_1 <- function( game )
{  
   f_2( a=length(game) )
}
```

It just depends on what information is already being passed to functions and whether having fewer arguments to keep track of makes the code easier to manage.

**Comment by lecy** [comment]
I would not hard-code a default value for the door number if you know the game size is changing.

```
build_doors <- function( n=10)
```

Note that the three functions that need doors are select_door(), open_goat_door(), and change_door(). 

The first two already have **game** as an argument. You could add **game** to the third and get size that way. You just need to make sure size is available somehow. You can’t derive it from switch, a.pick and opened.door - the three arguments used by change_door().

**Comment by gmendez9** [comment]
Hmm.. I've attempted to remove the hard coding for the build_doors function at the onset and passing the number, as well as including the game argument for Change_door function and including size, but returning this error: Error in build_doors(n = length(game)) : 
  argument "game" is missing, with no default. I can post the updated code :

build_door changes

```{r}
# create game function - STEP 2

num.goats <- 7
num.cars <- 3

create_game <- function( num.goats, num.cars )  # <- NEW ARGUMENTS
{
    a.game <- sample( x=rep( c("goat","car"), c(num.goats,num.cars) ), 
                      size=(num.goats+num.cars), replace=F )
    return( a.game )
    
}



### build door function - STEP ONE


build_doors <- function( n ){ return(1: n ) }
```


Change_door function:

```{r}
change_door <- function( stay=T, game, opened.door, a.pick )
{
   doors <- build_doors(n=length(game))
   
   if( stay )
   {
     final.pick <- a.pick
   }
   if( ! stay )
   {
    available.doors <- doors[ doors != opened.door & doors != a.pick ]
     final.pick  <- sample( available.doors, size=1 ) 
   }
  
   return( final.pick )  # number between 1 and n
}

```

**Comment by lecy** [comment]
Note the function definition vs execution inside of play_game(): 

```r
# define the function
change_door <- function( stay=T, game, opened.door, a.pick )

# call the function inside play_game()
 final.pick.stay <- change_door( stay=T, opened.door=opened.door, a.pick=first.pick )
 final.pick.switch <- change_door( stay=F, opened.door=opened.door, a.pick=first.pick )
```

Do you see the difference in arguments? And why you would get: 

```
Error in build_doors(n = length(game)) :
argument "game" is missing, with no default.
```

**Comment by gmendez9** [comment]
> Note the function definition vs execution inside of play_game():
> 
> ```r
> # define the function
> change_door <- function( stay=T, game, opened.door, a.pick )
> 
> # call the function inside play_game()
> final.pick.stay <- change_door( stay=T, opened.door=opened.door, a.pick=first.pick )
> final.pick.switch <- change_door( stay=F, opened.door=opened.door, a.pick=first.pick )
> ```
> 
> Do you see the difference in arguments? And why you would get:
> 
> ```
> Error in build_doors(n = length(game)) :
> argument "game" is missing, with no default.
> ```

Yes, it appears we must also call the game argument inside the play_game() function as so :

```{r}


  final.pick.stay <- change_door( stay=T, opened.door=opened.door, a.pick=first.pick, game = new.game )
  final.pick.switch <- change_door( stay=F, opened.door=opened.door, a.pick=first.pick, game = new.game )

```
