### ISSUE TITLE
Final Lab - Part 2 

### ISSUE THREAD

**Issue by kdelaro2** [Watts-College/paf-514-template#90]
Hello!

I'm running into an issue when using the `build_graph()` for part II of the lab. Here is my code: 

```
for( i in academic.units )
{
  
  d2 <- filter( d, Department.Description == i )
  if( nrow(d2) == 0 ) { next }  
  # create the salary summary by rank & gender table 
  create_salary_table(d2)
  # create the top 5 salaries table 
  top_5_salaries(d2)
  # build the graph 
  build_graph( t.salary = d2, unit = "WPC Supply Chain Management")

  # print the tables:  
  #cat( paste('<h3>',"TOP FIVE SALARIES",'</h3>' ) )
  #cat( t.rank %>% knitr::kable(format="html") )   

  # cat( '<br><hr><br>' )
  
}
```
When I run this, I get an error saying: Error in plot.window(xlim = c(40000 - 10000, xmax), ylim = c(0, ymax +  : 
  need finite 'xlim' values

However, when I run the same `build_graph()` function for the d dataset, it runs perfectly so I'm not sure where the disconnect is?

**Comment by castower** [comment]
@kdelaro2 
You'll notice that in the examples for the lab there are pipes between the individual functions. You'll want to do this here and make the "unit" value a variable. You currently have the unit as a fixed value so if it isn't in the data set you'll get an error. You also aren't passing the output of the previous functions into the next step because they're all run as individual functions rather than saving the output or passing with pipes.

See examples:
```
d %>%  
  filter( Department.Description == "Psychology" ) %>% 
  create_table( ) %>% 
  build_graph( unit="Psychology" )
```

If unit is variable 'i' then:

```
  d %>%  
    filter( Department.Description == i ) %>% 
    create_salary_table() %>% 
    build_graph( unit=i )  
```

**Comment by kdelaro2** [comment]
Got it, thank you!

**Comment by CTNovoa** [comment]
Thanks, @kdelaro2, your post was helpful. However, I am still getting the following error:

![image](https://github.com/user-attachments/assets/60b688e0-56c4-487c-a0d4-7068761608e6)


```````{r, fig.height=7, fig.width=10, results="asis"}
for( i in academic.units )
{
  d2 <- filter( d, Department.Description == i )
  if( nrow(d2) == 0 ) { next }  
  
  print (i)
  
#  d %>% 
#  filter( Department.Description == i ) %>% 
#  create_salary_table( ) %>% 
#  build_graph( unit=i ) %>% 
#  Top_Five_Salaries(d) %>%  pander()
 
  t.salary <- 
  d2 %>% 
  group_by( title, gender ) %>% 
  summarize( q25=quantile(salary,0.25),
             q50=quantile(salary,0.50),
             q75=quantile(salary,0.75),
             n=n() ) %>% 
  ungroup() %>% 
  mutate( p= round( n/sum(n), 2) )
  
  t.salary %>% 
   create_salary_table() %>% 
   build_graph(unit=i)


 t.salary$q25 <- dollarize( t.salary$q25 )
 t.salary$q50 <- dollarize( t.salary$q50 )
 t.salary$q75 <- dollarize( t.salary$q75 )

# print the tables
 cat( paste('<h3>',"TOP FIVE SALARIES",'</h3>' ) )
 cat( t.salary %>% knitr::kable(format="html") )
 
 cat( '<br><hr><br>' )
}
````
