### ISSUE TITLE
Final Lab - Get Data

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/paf-514-template#91]
For some reason, when I run the batch file, it just stops at 67% and won't actually create the report files. Any thoughts as to why this might be happening? I have double-checked my working directory and restarted my session: 

![image](https://github.com/user-attachments/assets/918e476f-1d67-40b5-948c-1937a5a7dbc1)

Thank you!

**Comment by castower** [comment]
@CTNovoa Does the run ever finish? Sometimes the gender merge step can take a little while to load the gender data.

**Comment by CTNovoa** [comment]
It didn't - however, I tried updating my packages and version of R and now have received this error when attempting to run the 2020 report: "Error: params object already exists in knit environment so can't be overwritten by render params"

**Comment by CTNovoa** [comment]
Okay, they seem to be created as values now in the R environment. Apparently I just needed to do some updates! Apologies for the trouble. It is saying that it can't find the function "build_url ( ) " is that from the "rwunderground" package?

**Comment by ioxoiperez27** [comment]
Hello, do you think you can give me insight on how you got yours to work? 
I am having a similar issue where mine also stops at 67% 

![Screenshot 2024-10-09 205319](https://github.com/user-attachments/assets/5d2475e7-a5c5-4e10-8842-3c778e99a78d)

**Comment by CTNovoa** [comment]
Absolutely! I ended up updating my packages. I went to tools > check for package updates. I also restarted my R session. I hope that ends up doing the trick for you!

![image](https://github.com/user-attachments/assets/98f4e6cc-9814-4c5c-876e-c687bcb2e5f2)

**Comment by shumway99** [comment]
Not sure if anyone is still up, it's late out here for me on the East Coast haha, but it looks like some people just made comments, so hopefully somebody is! I am getting a similar problem, but instead of just stopping at 67% it's asking for a Selection in my console. Any idea what I need to put there? Am I having a blonde moment haha? I have updated R, RStudio, and all the packages. 
![image](https://github.com/user-attachments/assets/210abbc0-16fa-4849-a3f1-11d7aa0a8718)

**Comment by castower** [comment]
Hello @shumway99 ,
Have you already installed the gender packages? It may be that they're attempting install.

**Comment by shumway99** [comment]
Lol yes that was the problem! I figured it out right before you responded haha but thank you!!

**Comment by CTNovoa** [comment]
I have installed the gender package, but now I am continually getting a prompt from my RStudio asking if I want to download the "genderdata" package? I have tried to select "yes," but it doesn't seem to be doing anything. When I try to download this separately there doesn't seem to be a "genderdata" package. I have installed and loaded the "gender" package.

**Comment by castower** [comment]
@CTNovoa 

The install step is at the very beginning of the lab under 'packages'

```
remotes::install_github("lmullen/genderdata")
```

The package isn't in CRAN so you have to download from GitHub.

Here is the GitHub page: https://github.com/lmullen/genderdata

**Comment by CTNovoa** [comment]
Ah, yes. Thank you! 

It successfully installed gender, but not "genderdata" 
![image](https://github.com/user-attachments/assets/2d187c2f-7a1c-4877-a773-49abf80ba2b8)

**Comment by castower** [comment]
@CTNovoa 

You can try entering just the genderdata step directly in the R Console instead of running from the code chunk. If it continues to give errors, you can download the tarball file linked in the lab (just right-click to download the zip) and then install locally.

**Comment by CTNovoa** [comment]
The local download seemed to finally work! Thank you so much for taking the time; apologies for the trouble here.

**Comment by castower** [comment]
@CTNovoa yay! Glad that worked
