### ISSUE TITLE
Final lab part 2

### ISSUE THREAD

**Issue by pmorrizonaz** [Watts-College/paf-514-template#93]
Hi @castower 

I'm running into an issue with my for loop in the function demo. Here's what I have so far:

for (i in academic.units) {
  d2 <- filter( d, Department.Description == i )
  if( nrow(d2) == 0 ) { next }  
 
  salary_table <- create_salary_table(d2)
  print(salary_table)
  
  top_salaries_table <- top_five_salaries(d2)
  print(top_salaries_table)
  
  salaries_graph <- build_graph(d2, i)
  print(salaries_graph)
}

When I run it, I get an error saying "returning -InfError in plot.window(xlim = c(40000 - 10000, xmax), ylim = c(0, ymax +  : need finite 'xlim' values". But since the code for the build_graph() function was provided, I'm not sure why the error is occurring. Thank you for any help!

**Comment by castower** [comment]
Hello @pmorrizonaz 

You need to have the output from create_salary_table() to create your graphs. 

Specifically, the quartiles are needed for the graphs.
