### ISSUE TITLE
Final Lab - First Names

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/paf-514-template#94]
Likely a very silly question, but I am seeing someone named "Barton, C Michael" in the 2020 Data. This person's first name is "C," correct? 

Thus, the correct first name pull for them would indeed just be "C"?

**Comment by castower** [comment]
@CTNovoa Yes, correct. It'll be one of the outlier names that likely won't have a gender match.

**Comment by CTNovoa** [comment]
Thank you, @castower !
