### ISSUE TITLE
Final Lab- Part 1 Step 3

### ISSUE THREAD

**Issue by shumway99** [Watts-College/paf-514-template#96]
Hi @castower or anyone who can help :) Don't judge me, I am not as far on the final as I would like to be haha!

I have a question about merging the existing data with the gender table in Step 3. I'm trying to do a left_merge, which I'm not even sure is the right thing to do, but it keeps telling me that "first.name", or whatever I choose to merge by, needs to exist in both datasets, which makes sense, but I thought that first.name did exist in both? Here is my code:

#here's where I'm extracting the first name:
get_first_name <- function(x)
{
  split_name <- strsplit(x, split = ",")
  trim_white_space <- trimws(split_name)
  split_name_vector <- unlist(trim_white_space)
  first_name <- word(x, 2)
  return(first_name)
}

d$first.name <- get_first_name( d$Full.Name )

#here's where I'm creating the gender table:
add_gender <- function(x){
  first.name <- get_first_name(x)
  unique.first.names <- unique(first.name)
  gender_table <- gender(unique.first.names)
  return(gender_table)
}

gender <- add_gender(d$Full.Name)

#and then here's where I'm trying to left join, but then I keep getting the following error message:
d <- left_join(d, gender, by="first.name")
d$gender[is.na(d$gender)] <- "Uncoded"
d$gender <- factor(d$gender, levels = c("male", "female", "uncoded"))

![image](https://github.com/user-attachments/assets/7b5337df-9bb2-4e86-ae9e-c9ff0374b0c8)

Any help would be much appreciated!

**Comment by ClaudiaHebert** [comment]
In the gender dataset it's just called name! What I did was rename it to first.name within my add_gender() function before merging:

gen <- gen %>% 
    rename(first.name = name)

**Comment by castower** [comment]
@ClaudiaHebert is correct.

@shumway99  You can review the data joins section of the lab's help section for examples of how to merge with different named columns.

**Comment by shumway99** [comment]
That worked! Thank you!!!
