### ISSUE TITLE
Final Lab - Part 1 Step 10

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/paf-514-template#97]
Hello! I am not sure why I am having so much trouble with what should be a very simple task, but I can't seem to figure out the best way to get the output of a table for **Part 1 Step 10.** I have been able to "dollarize" my salaries so that they are displayed as currency again and I am able to select my top 5 highest salaries within my data. However, I can't seem to figure out the best way to get this to display as a table with only the Full.Name, gender, Job.Description, and salary columns displayed of only those top five highest salaries.

Can someone help me with this odd lapse in my thinking? I have tried so many different table creation functions and for some reason I can't seem to find quite the right fit. 

Thank you so much!

**Comment by ClaudiaHebert** [comment]
Did you try select() to choose the columns? and then I used head(5) within the function to output just the top 5.

But the function itself doesn't return a table, I still have to assign it to something and then print it like below, is that not the right process? 

top_five_salaries <- top_five_table(d)
print(top_five_salaries)

**Comment by CTNovoa** [comment]
Thanks @ClaudiaHebert for chiming in :) That is similar to what I was trying, but I know the assignment says: "Create function that generates a table of the top 5 salaries and reports the name, gender, position, and salary of each person on the list." So I was also trying to figure out a way to generate  table that only had those 4 columns of data within it.

**Comment by CTNovoa** [comment]
I think I _may_ have gotten this working as expected. I ended up doing the following:

Top_Five_Salaries <- function(d)
 {
 d %>% 
 arrange (desc(salary)) %>% 
 top_n(5) %>% 
 select(c("Full.Name","gender","Job.Description","Salary"))
 }

Feel free to correct me if my thinking seems off on this :)

**Comment by castower** [comment]
Hello @CTNovoa ,
Yes, perfect :)
