### ISSUE TITLE
Final Lab - New salary

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/paf-514-template#98]
When I am creating my numeric salary vector, I am getting some strange errors depending on the year of data I am working with.

For example, in my 2016, 2017 & 2019 data, I am finding that some salaries have only 1 zero after the decimal point (e.g., $4,107.0) and in my 2018 & 2020 data, I am finding that some salaries will have three zeros (e.g., $4,107.000). Thus, far I cannot find anything in common with the entries that are causing this error...

The vast majority of salaries in all datasets (2016 -2 2020) are correct and have 2 numbers after the decimal point. 

I have tried updating my unstring_salary() function to specifically round to 2 decimal points, but that doesn't seem to be doing anything.

Did anyone else run into this and find a good solution? Thank you! Good luck on the final, everyone!

**Comment by castower** [comment]
@CTNovoa 
One option is to fix the decimal portions of the salaries within the strings before converting to a number.

**Comment by CTNovoa** [comment]
Yeah, I was attempting some of these functions before (though the article you passed along is much more helpful than the ones I had found--thank you!). However, even though I am trying to convert back to a number, I keep getting errors such as:

"Error in sprintf(x, fmt = "%.2f") : 
  invalid format '%.2f'; use format %s for character objects"

I was trying something like this:

unstring_salary <- function(x)
{
  x <- trimws(x)
  x <- gsub( "[$,]", "", x )
  x <- sprintf(x,fmt = '%.2f')  # Round to two decimal points
  x <- as.numeric( x )
  return(x)
}

Thank you so much, @castower !

**Comment by castower** [comment]
@CTNovoa You can simplify it a bit more by using something like the following (just update it to work within your function:
```

# Format salary strings with 2 decimal points, remove white space
format_salary <- stringr::str_trim(format(round(d$salary, 2), nsmall = 2))

# Format salaries as numeric
format_salary <- as.numeric(format_salary)

#View salaries
format_salary
```

**Comment by CTNovoa** [comment]
Thank you! Very helpful. I tried updating it as follows and am now getting the error of "Error in round(d$salary, 2) : 
  non-numeric argument to mathematical function"


unstring_salary <- function(x)
{
  x <- stringr::str_trim(format(round(d$salary, 2), nsmall = 2))
  x <- gsub( "[$,]", "", x )
  x <- as.numeric(x)
  return(x)
}

**Comment by castower** [comment]
@CTNovoa 

Did you run the fix_salary( ) function first? 

By default, R will remove removing trailing zeroes when converting to numeric, but you can adjust the strings with this code and then convert to numeric.
