### ISSUE TITLE
Final Project - Step 2

### ISSUE THREAD

**Issue by ClaudiaHebert** [Watts-College/paf-514-template#99]
@castower Two questions 1) At the end of Part I we're instructed "once all of your functions are working properly copy them all into the utils.R script." 

I did this for the newly created functions but I noticed some of the functions I created (such as add_gender() and get_first_name()) are already in the utils.R script -  Should we override these with the functions we've written? Or are we meant to leave them as is and just not add our functions? 

2) Where are the loops that go through the departments meant to go? In the original markdown file where we created the functions? or utils.R? or somewhere else?

**Comment by castower** [comment]
@ClaudiaHebert 

Reopening this in case any other students have the same questions!

1. You can comment out the old ones and add yours if you'd like to use your custom versions.
2. You'll want to add the loop to the final salary-report.rmd file and your demo .rmd file
